### ISSUE TITLE
Trakt sync failed for show with seasons named after released date

### ISSUE THREAD

**Issue by seyguai** [UweTrottmann/SeriesGuide#1049]
**Describe the bug**
The application cannot synchronize to trakt a watched episode for the show "Running Man".

**To Reproduce**
1. Connect to Trakt.Tv
2. Add Running man as show
3. Just set the next episode as watched

**Expected behavior**
It should work.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10+
 - OS: Android 12
 - Browser: Chrome
 - Version: 127.0.6533.103

**Additional context**
After some debug, it seems the app tries to synchronize season 1 episode 1, while on Trakt it is referenced as season 2010 episode 1:
https://trakt.tv/shows/running-man/seasons/2010/episodes/1 <- first episode
https://trakt.tv/shows/running-man/seasons/2024 <- last season
https://trakt.tv/shows/running-man/seasons/0 <- specials

In `com.battlelancer.seriesguide.jobs.TraktEpisodeJob#getEpisodesForTrakt`, `jobInfo.episodes(i).season()` returns `1`.
When calling the trakt api here: https://api.trakt.tv/shows/33093/seasons
I get this response:
```
[
  { "number": 0, "ids": { "trakt": 127477, "tvdb": 548446, ... } },
  { "number": 2010, "ids": { "trakt": 124501, "tvdb": 660063, ... } },
  { "number": 2011, ... },
  ...
]
```

I can probably keep investigating later, but it might be faster for you to fix it given the API response (first time debugging an android app).

**Comment by UweTrottmann** [comment]
Thanks for reporting! SeriesGuide uses TMDB as the data source and Trakt still uses TVDB for that show. But episodes on TVDB appear to be organized differently: https://trakt.tv/transition/tmdb/shows?trakt_id=33093

This probably requires some manual changes from the folks at Trakt. You can try to contact their support about this!

**Comment by seyguai** [comment]
Indeed, I'll try reaching them as soon as I figure their support portal.
Thx !
