### ISSUE TITLE
Favorite shows not visible in added list

### ISSUE THREAD

**Issue by HyperCriSiS** [UweTrottmann/SeriesGuide#1063]
**Describe the bug

Hi, 
It happens sometimes that not all favorite shows are shown in the added list. 
I still can find them via the search.
Filter reset does not help. 
I also cleared the app cache. 
I had this issue some weeks ago.
Some days later they were suddenly shown again. 🤔 

Best regards 
Hyper 

**Smartphone (please complete the following information):**
 - Device: Zenfone 8
 - OS: Android 11

**Comment by UweTrottmann** [comment]
When resetting the filter hidden shows are still not shown. Are these shows maybe hidden?

**Comment by osman160128** [comment]
hello maam, I want to solve this problem, but when I clone the repository from here,It showes that the app cannot talk to Database

**Comment by UweTrottmann** [comment]
@HyperCriSiS If they do show up in search and you can open them to view details, they must be included in the Added list if no filters are enabled. So just double checking: you did re-set both the regular filters and the Stream and purchase filters?

@osman160128 This is nothing I need help with, but thank you. If there are issues with setting up the project, please create a separate issue. Also make sure to check [the contributing instructions](https://github.com/UweTrottmann/SeriesGuide/blob/dev/CONTRIBUTING.md).

**Comment by HyperCriSiS** [comment]
> @HyperCriSiS If they do show up in search and you can open them to view details, they must be included in the Added list if no filters are enabled. So just double checking: you did re-set both the regular filters and the Stream and purchase filters?
> 
> @osman160128 This is nothing I need help with, but thank you. If there are issues with setting up the project, please create a separate issue. Also make sure to check [the contributing instructions](https://github.com/UweTrottmann/SeriesGuide/blob/dev/CONTRIBUTING.md).

Oh man, thank you. Somehow something was ticked on the streaming filter.
But that's strange, it happend two times now and I never use the filter...
Also last time the filter was set and reset without me doing anything. 😐
Whatever, the shows are now visible again 👍
