### ISSUE TITLE
[Feature Request] - Display the count of shows in a list.

### ISSUE THREAD

**Issue by raghav-0070** [UweTrottmann/SeriesGuide#1064]
Hi, 

First of all, I want to Thank you so much for creating this amazing application. Previously, I used to manage my shows by writing the last watched in a notes(haha!). Then tried to manage with Notion, but it was all so tedious as sometimes I forgot to note them and comeback to the series not knowing where I left off! Finally, 6 months ago, I found this app and it was a gamechanger to track my shows.

## Current Feature
Having said that, I have one feature request. As of now, I organized all my shows perfectly with the "Lists" Feature, like watching dramas, watching anime, completed dramas, paused, etc, etc, ...
![photo_2024-10-30_12-59-22](https://github.com/user-attachments/assets/c742b91d-e889-4716-9a5d-46236f1cc0ad)

## Expected Enhancement
But I also like to know how many shows i am watching, how many i have already watched, how many i have paused and all. So, it would be amazing if you can add the count of items beside the name of the list. Something like shown below
![{F5E1BE27-97A6-4190-ADFE-51AF73DD49ED}](https://github.com/user-attachments/assets/db25cf0f-2b9b-4112-bfa6-a838154c8532)

Hoping you will consider this. 
Thank you,
Raghav.

**Comment by UweTrottmann** [comment]
Thanks for the suggestion! I recommend posting ideas and suggestions to the Community instead, so other users can like it. If you decide to, please close this issue.
