### ISSUE TITLE
[trakt] Option to add shows to watchlist

### ISSUE THREAD

**Issue by coulz** [UweTrottmann/SeriesGuide#188]
Since you add the watchlist tab in the app, I think it would be great to add an option to put a show in our trakt watchlist, why not adding this option when we long press a show in the add screen?

**Comment by raynotroy** [comment]
I think this feature is desperately needed.  There are many votes on UserGuide and it clearly must be possible to add the TV Show watchlist integration just like the Movie watchlist integration.  When I find a new Movie I want to watch I add it to my watchlist in SeriesGuide.  When I find a new TV Show I want to watch I have to go to the trakt.tv website.

**Comment by matthewdias** [comment]
I think this has more to do with the philosophy of the app as a whole. It seems like it wants to be more of a standalone manager that has the option of importing from Trakt, rather than a client for Trakt that maintains parity.

**Comment by UweTrottmann** [comment]
Will ship with release 30.
