### ISSUE TITLE
More data sets for widget

### ISSUE THREAD

**Issue by TomPastyrik** [UweTrottmann/SeriesGuide#213]
Hi!

First of all thanks for your amazing work on this, I have gladly supported you by buying X version.

However, there is what I am missing badly - I do use this app for tracking my progress in shows that has been already published. You have a data set showing next unseen episode of each show to be displayed on homepage. I am not sure what you call this data set in English version, it's third option in select on homepage. 

It would be great to choose this set to be displayed by widget! :)

Thanks for your work!
Tom

**Comment by UweTrottmann** [comment]
Closing this generic issue in favor of specific requests.
