### ISSUE TITLE
Time is off 1 hour between show list and activity screen

### ISSUE THREAD

**Issue by UweTrottmann** [UweTrottmann/SeriesGuide#218]
Android version: 4.0.4
Device: HTC One X
Language: English (United States)
Time Zone: Set on phone to automatic time zone; I am in the Central time zone; on the app, I have it set to offset by 0 hours

More information:
When I go to the app, on the main page, the times are correct. However, when I go to the activity page, the time is off by +1 hour. The widget seems to be pulling it's information off of this screen, and thus the wrong information is on the widget.

**Comment by tonyp** [comment]
Just confirming that this is fully fixed now, supposedly with v21 (and the EST fallback for non US users).
Thanks!
