### ISSUE TITLE
Switching seasons using ActionBar dropdown

### ISSUE THREAD

**Issue by novemberox** [UweTrottmann/SeriesGuide#246]
Hi,

I'd love to have possibility to switch season on screen with list episodes. I was thinking that it would be nice to be able to use ActionBar.NAVIGATION_MODE_LIST to display list of seasons and quickly switch it. 

Reason of this request is that I watch "whose line is it anyway" in random order and I often check if I already watched that episode, and it's pain to click back and select another season.

I could write pull request if you like that.

Best
Miko

**Comment by UweTrottmann** [comment]
Will ship with `30-beta3`.
