### ISSUE TITLE
Do not notify if show is hidden

### ISSUE THREAD

**Issue by coulz** [UweTrottmann/SeriesGuide#373]
Hi, 
With SeriesGuide 12.2 with X subscription, the app notifies for all new episodes as I have asked but it includes the episodes from my hidden shows. Could you please fix it? Thanks.

**Comment by AlexGThess** [comment]
Its better to still get notified from hidden shows if those shows has enabled the notification alert.
if the notification alert for the show its unselected, then not notified. (hidden or not)
