### ISSUE TITLE
Movies without release dates are sorted first, not last.

### ISSUE THREAD

**Issue by JakeWharton** [UweTrottmann/SeriesGuide#416]
I think they should be sorted last since as far as I can tell they're all movies in the future.

![2014-12-21 09 35 45](https://cloud.githubusercontent.com/assets/66577/5517761/ced35f2e-88b1-11e4-9ff2-d38e81dced23.png)

**Comment by UweTrottmann** [comment]
Database sorts by release date (long instant), so
- [ ] set release date to Long.MAX if unknown
- [ ] display "unknown" release date for movies with Long.MAX release date
