### ISSUE TITLE
Trakt Update

### ISSUE THREAD

**Issue by S7eele** [UweTrottmann/SeriesGuide#417]
I couldn't get into the community forum so trying this method. I am very familiar with trakt and have been eagerly awaiting the upgrade, especially v2 of the API. I am assuming the recent upgrade has caused the problems I am seeing. Essentially no communication with trakt via SeriesGuide. Have enjoyed using your app and happily paid the unlock cost. Just like to know if I'm correct wrt trakt and wonder what your plans may be if I am. Please advise.

**Comment by KevOrr** [comment]
They have occasional updates on [their API's twitter account](https://twitter.com/traktapi), but it seems initial support for the v1 methods was none or close to it. Anyway, if you want in on their API's G+ community, current instructions are to [shoot Justin <justin@trakt.tv> an email](mailto:justin@trakt.tv).

**Comment by UweTrottmann** [comment]
Please look at the SeriesGuide G+, Facebook or Twitter accounts (see seriesgui.de for links) for updates. Otherwise write me a mail (see Play store).

**Comment by S7eele** [comment]
Thanks, I don't really use any of the social media sites you mentioned but will now be checking them out to stay up to date. Appreciate your quick response Uwe and I'm also grateful for your input KevOrr.
