### ISSUE TITLE
HTTP 422 when connecting to trakt

### ISSUE THREAD

**Issue by drllama** [UweTrottmann/SeriesGuide#421]
I only get a 422 error when setting up trakt login (3 days now). Trakt support suggested i contact you here with the problem, it is the same probkem as ticket 418, email below:

Alright, I'm on the same version too and was able to connect right now. I think we've ruled out a trakt account problem since you can log in through other services.

From looking at Uwe's support ticket (linked below), it looks like it is api server problems.  I'll look into it, but currently they're looking pretty stable.  Could honestly be bad timing.  If you continue to get this error, I'd bring it up with Uwe on github and see if he can narrow it down.

**Comment by UweTrottmann** [comment]
Have you tried with SeriesGuide 21.0.4? How are you signing in, with trakt user + password or Twitter/Facebook/G+?

**Comment by drllama** [comment]
Using 21.0.4, signing in with a trakt account, account works on web site and using mediaportal for windows, and was working fine with trakt v1. I also cleared data in seriesguide to start fresh, still no joy.

**Comment by UweTrottmann** [comment]
Ok, what device and Android version are you using?

**Comment by drllama** [comment]
Samsung Galaxy TAB S 4.4.2 Rooted, just tried it on my phone Galaxy Note 2 (4.3 Unrooted) and it worked. Still can't connect on the tab s though. Can't see why one would work and one not.

**Comment by drllama** [comment]
Samsung Galaxy TAB S 4.4.2 Rooted, just tried it on my phone Galaxy Note 2 (4.3 Unrooted) and it worked. Still can't connect on the tab s though. Can't see why one would work and one not.

**Comment by UweTrottmann** [comment]
Sorry, no. If it works on your Note it is likely a device specific issue.

Does your email address or password contain any special characters? I wonder if it is an encoding issue. If so, try to change it to just numbers and letters.

**Comment by drllama** [comment]
__Fixed it.__ It must have been something else installed - I did a hard reset & reinstalled just the basics and seriesguide and it works now. I will now spend some time to see if I can track down what I had installed that was causing the problem (this may take some time, I had a lot installed).

**Comment by UweTrottmann** [comment]
Have you been using any proxy software or VPN?

Uwe

**Comment by outlyer-net** [comment]
For the record, I encountered the same 422 error repeatedly.
In the end the source of the problem was AdBlock (which acts as a proxy). Disabling its filtering temporarily, allowed me to connect to trakt without trouble.

**Comment by UweTrottmann** [comment]
@outlyer-net Totally forgot to thank you, solved issues with other users as well!
