### ISSUE TITLE
[trakt] Outdated data after sync + Sync not working

### ISSUE THREAD

**Issue by papjul** [UweTrottmann/SeriesGuide#425]
Hello,

First of all, I'm using French UI so some messages might not be translated exactly as it is in English UI. Plus, when I say check I mean marked as seen, I don't use the check-in feature.

I noticed today after going on a TV show details, that it updated seasons and episodes as it always does, but this time lots of episodes were removed from “seen” in front of my eyes, even random episodes from other seasons that I watched months, maybe years ago. It happened to lot of TV shows but I will just take one as example: Case Closed.

Some episodes from season 7, half from season 22, and the whole season 23 were marked unseen. So I looked on trakt and indeed they weren't marked seen. So I checked all seen from season 7 and 22, and checked first episodes from season 23 that I did watch. I got message “7x seen. Sending to trakt” as I always get. No error from catlog. I got back on trakt, season 7 was OK, season 22 and 23 were still missing. You can see in my history that I indeed just checked episodes from season 7: http://trakt.tv/users/yurienu/history and that season 22 and 23 are missing: http://trakt.tv/users/yurienu/progress

I tried again a lot of times to mark season 22 seen but I kept getting the Sending to trakt message with no error.

Is it possible that it has something to do with international titles?

Thank you for your help,

**Comment by UweTrottmann** [comment]
trakt server might have been busy. The next SeriesGuide release will have
improved error messages.

**Comment by papjul** [comment]
Do you know how come episodes I watched months ago disappeared? Why didn't it sync a few days after, instead of months after? I have a TV show with 7 seasons where almost all episodes were removed from seen.

**Comment by papjul** [comment]
I can confirm that touching Season 22 seen worked just now. But SeriesGuide showed me All episodes from season 22 while it wasn't until I touched it. Is there a way to not put seen in SeriesGuide until it synced for trakt users?

**Comment by papjul** [comment]
After some days of testing, looks fixed to me with latest version. Issue closed, thank you very much.
