### ISSUE TITLE
Duplicate "Special Episodes" season

### ISSUE THREAD

**Issue by UweTrottmann** [UweTrottmann/SeriesGuide#426]
[Reported on G+](https://plus.google.com/b/112462818579768957964/105027671081444739173/posts/akC8oP73rGb)

Looks like TheTVDB is sending episodes that don't belong to a proper season. Investigate what is going wrong, if we should prevent/handle this.

**Comment by flabbamann** [comment]
Hi, I am pretty sure it is the same problem as here:

http://forums.thetvdb.com/viewtopic.php?f=18&t=17904

**Comment by UweTrottmann** [comment]
@flabbamann thanks very much for pointing this out! Looks like someone also already reported it, as I don't get the additional episodes from the API any longer.

Keeping this issue around for reference, renaming it.

**Comment by UweTrottmann** [comment]
No need for this to be open, was solved as a TheTVDB issue.
