### ISSUE TITLE
Unwatched filter doesn't work

### ISSUE THREAD

**Issue by Eisfreak7** [UweTrottmann/SeriesGuide#430]
Hi
I am new to this app so it might be that I just misunderstand the filter, but as far as I understand it it should only show shows with unwatched episodes. However, when I apply it *all* shows (including those with unwatched episodes and those with all episodes unwatched) are hidden. I suppose that's not how its intended. Since I see nobody else reporting this, maybe it was introduced in today's update.

**Comment by UweTrottmann** [comment]
Thanks for your report. Could you share some screenshots?

The filter system has not changed in a while, so either it's a device issue
or as you said a misunderstanding.
Am 22.01.2015 21:48 schrieb "Eisfreak7" <notifications@github.com>:

**Comment by Eisfreak7** [comment]
Of cause. Unfortunately I could't find an option to set the GUI to english, so the screenshots are in German. But it should be understandable.
Here you can see that the series are in my list:
![screenshot_2015-01-23-16-43-48](https://cloud.githubusercontent.com/assets/3799330/5877552/a6f5f85c-a320-11e4-8cbf-ec72209a4777.png)

Here you see that at least one of the series in the list has multiple unwatched episodes:
![screenshot_2015-01-23-16-44-01](https://cloud.githubusercontent.com/assets/3799330/5877568/bc3f0dc0-a320-11e4-88ae-11eb88e10c9a.png)

And, finally, here is the empty list with the filter applyed:
![screenshot_2015-01-23-16-44-12](https://cloud.githubusercontent.com/assets/3799330/5877570/c0e2ae7c-a320-11e4-8ad3-c4ad561baae0.png)


I'm using the OnePlus One.

**Comment by UweTrottmann** [comment]
Ah,  verstanden. Der Filter sieht sich nur die als nächste deklarierte
Folge an, diejenigen, die man auch in der Liste sieht.

Wahrscheinlich ist in den Einstellungen aktiviert, nur zukünftige Folgen
als nächste anzuzeigen. Einfach deaktivieren, dann sollte es klappen.

**Comment by Eisfreak7** [comment]
Ah ja der Fehler war die Einstellung "Keine gesendeten Folgen" (ich nehme an die meintest du). Ich hatte die so interpretiert, dass sie nur für den "demnächst" tab gilt. Mein Fehler.
Danke.
