### ISSUE TITLE
Beta app download 

### ISSUE THREAD

**Issue by MarkLaViolette** [UweTrottmann/SeriesGuide#432]
I joined your beta program a couple of ours ago and I still can't seem to download your beta app. How long will it take before it is available for me to download and test?

**Comment by UweTrottmann** [comment]
Responded already via email. For reference:

As Google says on the [testing page](https://play.google.com/apps/testing/com.battlelancer.seriesguide) it can take up to a few hours.

Try installing it via the Play store website. Or try clearing the Play store app cache (in Android Settings, go to Apps, find the Play store and then "Clear Cache").

You can also try leaving and joining again.
