### ISSUE TITLE
Option to select and rearrange tabs

### ISSUE THREAD

**Issue by JLB88** [UweTrottmann/SeriesGuide#437]
There are quite a few tabs that I do not use, which create unnecessary clutter. It would be nice if you could make an option to hide and rearrange them.

**Comment by UweTrottmann** [comment]
I assume you mean the tabs in the shows section, but could you be more specific? E.g. if you are not connected to trakt, those tabs should not be visible.

**Comment by JLB88** [comment]
Indeed, for the shows section, but this would also work well in the movies section. I am connected to trakt, but I do not particularly care for the 'now' or 'history' tabs. The same goes for movies.

**Comment by UweTrottmann** [comment]
Added ability to re-order Lists tabs. For now, no plans to allow re-ordering of other UI tabs.
