### ISSUE TITLE
Next episode sometimes calculated incorrectly

### ISSUE THREAD

**Issue by UweTrottmann** [UweTrottmann/SeriesGuide#440]
_Reported via mail, 2 incidents, same user_

**Can't reproduce.**

After adding a show a later than the first episode is calculated as the next one.

Notes
- Not connected to trakt or SG Cloud (maybe sync did unset previously watched episode, causing issue).

**Comment by UweTrottmann** [comment]
Another user report, now with steps to hopefully reproduce:

> Here's one scenario that is consistent:
> Castle (2009)
> 
> In the shows list it displays
> 
> Castle (2009)
> 6x09 Disciple
> Nov 18, 2013 (Mon)
> 
> If I go into Castle and look at Seasons:
> I've watched all of Seasons 1 - 5
> Season 6 has 2 episodes not watched (#9 & #22 out of 23 episodes)
> Season 7 has all episodes watched
> Season 8 has 2 episodes not watched (+5 unaired) The 2 unwatched episodes are the last 2 aired)
> Season 9 has 1 unwatched episode Release date unknown (because season 8 is currently airing)
> 
> I have at least 2 other examples where this happens.
> 
> A simpler one:
> Season 1 has 5 episodes not watched (#1, 4, 5, 13, 16) out of 20 episodes
> Season 2 has (2 other episodes) ie watched episodes 1-20, episodes 21 & 22 are release date unknown)
> In the show listing:
> 1x01 Pilot
> Sep 13, 2014 (Sat)

**Comment by JohnNickerson** [comment]
This could be the bug I'm seeing right now. 

Show: Buffy the Vampire Slayer
Watched in order up to season 3 episode 17
Next episode listed on the "Shows" tab is season 3 episode 19
![Screenshot_20230223_130408_SeriesGuide](https://user-images.githubusercontent.com/5936158/220814712-9d40a8fc-c142-4504-8aa4-e3fa5605cfe9.jpg)

In the Episodes view for season 3, episode 18 is still marked unwatched.
![Screenshot_20230223_130423_SeriesGuide](https://user-images.githubusercontent.com/5936158/220814717-62f8c502-13da-420f-8662-a20661db3964.jpg)
n 3, episode 18 is still marked unwatched.

 If I mark it as watched, 
![Screenshot_20230223_130430_SeriesGuide](https://user-images.githubusercontent.com/5936158/220814763-471d50ec-56a8-48dd-94c9-c6ab8d752919.jpg)

the "next" unwatched episode on the "Shows" tab is season 4 episode 1.
![Screenshot_20230223_130437_SeriesGuide](https://user-images.githubusercontent.com/5936158/220814782-d5c49a18-5d4a-451a-aeaa-b8c047977b98.jpg)

**Comment by UweTrottmann** [comment]
SeriesGuide chooses the next episode [based on the release date](https://github.com/UweTrottmann/SeriesGuide/blob/a1fc7d6a2a5d4945dc552a5d515202f260caf6af/app/src/main/java/com/battlelancer/seriesguide/shows/tools/NextEpisodeUpdater.kt#L94-L98), not the episode number. This is to support shows where special episodes (from season 0) are released in between regular episodes.

In this case it looks like episode 19 was released before episode 18 (May vs. September of 1999). If this is not correct, feel free to correct/report this at https://www.themoviedb.org/. If it is correct, than this is an unfortunate edge case.

**Comment by JohnNickerson** [comment]
I see. No, those release dates are correct. Episode 18 was released after the rest of season 3, so this is just one of those edge cases.

**Comment by UweTrottmann** [comment]
Closing this then as I have not received any other reports on this (issue is from 2015 after all).
