### ISSUE TITLE
Use mipmaps for launcher icons

### ISSUE THREAD

**Issue by ming13** [UweTrottmann/SeriesGuide#448]
Probably should provide better launcher experience for the Google Now launcher. [Some Google mambo jambo](http://android-developers.blogspot.com/2014/10/getting-your-apps-ready-for-nexus-6-and.html).

**Comment by UweTrottmann** [comment]
SG uses them as drawable in some places in the app, hence I never moved them. But I guess adding a xxxhdpi mipmap won't hurt.

**Comment by ming13** [comment]
Hmm, can [`<bitmap>`](http://developer.android.com/guide/topics/resources/drawable-resource.html#Bitmap) help? I mean placing launcher icons to `mipmap` directories as `ic_launcher.png` and reference them from `drawable` directories as `ic_launcher.xml` which will contain something like this.

```xml
<?xml version="1.0" encoding="utf-8"?>
<bitmap xmlns:android="http://schemas.android.com/apk/res/android"
    android:src="@mipmap/ic_launcher"/>
```

Or even vice versa, `<bitmap>` has `android:mipMap` field.

**Comment by UweTrottmann** [comment]
Possibly. Ok, this is a no-go as mipmaps are only supported from Android 4.3 and up. But SeriesGuide is currently supporting 4.0 and up...

**Comment by ming13** [comment]
Well, duplication is the only way then :thought_balloon: Maybe it is not worth it at all. Just tried to use mipmaps on a Nexus 4, the Google Now launcher still uses an icon from the `mipmap-xhdpi` directory.

**Comment by UweTrottmann** [comment]
I don't think duplication works. AFAIK it is not possible to create a version specific manifest (where the launcher icon has to be specified) other than building a separate APK.

**Comment by ming13** [comment]
Actually I tried setting mipmap resource as a launcher icon and it worked fine for ICS. Probably build tools optimize the process somehow. It’s a shame there is no proper documentation about mipmaps.

Anyway, as I said earlier, there is no difference for Nexus 4 at least, so maybe the idea is kind of useless.

**Comment by UweTrottmann** [comment]
Yeah, documentation is sadly lacking... Thanks for looking into this!
