### ISSUE TITLE
F-Droid integration

### ISSUE THREAD

**Issue by varyoo** [UweTrottmann/SeriesGuide#456]
Please consider uploading releases to F-Droid.
Especially in this context of Google Play abuses.
Great app.

**Comment by UweTrottmann** [comment]
Thanks for the suggestion.

**Comment by zzzardoz** [comment]
Hi Uwe!

There's a request on fdroid to include SeriesGuide.

https://gitlab.com/fdroid/rfp/issues/208

Unfortunately it doesn't comply with their inclusion policy:

> - We cannot build apps using Google's proprietary "play-services". Please talk to upstream about an untainted build flavor (either using microg or removing non-free deps completely).
> 
> - We cannot build apps using proprietary tracking/analytic dependencies like Crashlytics and Firebase. Please talk to upstream about an untainted build flavor (either using a FLOSS analytics software like ACRA or by removing non-free deps completely).

Can you provide an untainted build flavor? Because your app is great, and I would love to see it on fdroid! :-)

**Comment by UweTrottmann** [comment]
Thanks for the enthusiasm 👍 But I want to focus on the Google Play/Amazon version as it allows me to make a living (at least part-time).

Though as the code is open, anyone should feel free to maintain a fork that removes Play services and Crashlytics.

**Comment by hovancik** [comment]
I would also love to see F-Droid support, but I understand your reasons. Thanks for the app.

**Comment by D3SOX** [comment]
I stumbled upon this issue while searching for an existing one for my following question: Would it be possible for you to provide a way to buy the premium version without Google Play services?

**Comment by UweTrottmann** [comment]
@D3SOX Theoretically, but requiring great investment and risk. Currently not worth for the few people that would use it.

**Comment by D3SOX** [comment]
@UweTrottmann I understand. Sadly there is no FOSS payment alternative for Android apps afaik
