### ISSUE TITLE
Movie/Show Suggestions via trakt

### ISSUE THREAD

**Issue by pironic** [UweTrottmann/SeriesGuide#459]
Since trakt's recent site wide update, the only way to access their movie/show recommendation engine is view the api. Since SeriesGuide is already OAuthed for a user, this provides a unique opportunity for SeriesGuide to be the first/easiest way for someone to take advantage of this feature.

Provide a section or feature called 'suggest a movie/show' in which the trakt recommendation engine is polled by SeriesGuide

http://docs.trakt.apiary.io/#reference/recommendations/get-watched-history

**Comment by UweTrottmann** [comment]
If connected to trakt, look in the "Recommended" tab in the "As show"
screen. However, as can be seen at
https://medium.com/@trakt/api-changelog-9f4041819718 recommendations are
not done, yet.

**Comment by pironic** [comment]
ahh, so that's why the api is suggesting i would enjoy the scientology
movie. ;-)

Glad to see you guys have this one on your radar though. I'm not sure on
your procedure for issues/enhancements, so feel free to close the issue for
now then.
