### ISSUE TITLE
"Set all older watched" not working for multiple episodes on one day

### ISSUE THREAD

**Issue by palantus** [UweTrottmann/SeriesGuide#463]
I'm using trakt sync and have the show Sense8 in my library. When I click on the overflow menu for any episode and select "Set all older watched", no episode is set as watched. I'm guessing that it's because all episodes of that show is aired the same date (Netflix).

**Comment by UweTrottmann** [comment]
Thanks, already had this on the internal bug tracker. Moving it here then.

**Comment by UweTrottmann** [comment]
[Suggestion](https://github.com/UweTrottmann/SeriesGuide/pull/516#issuecomment-299432315) by @gervasiocaj:

```sql
SELECT season, episodenumber FROM episodes WHERE (episode_firstairedms < 123) OR (episode_firstairedms = 123 AND episodenumber < 2)
```
