### ISSUE TITLE
Incorrect episode set watched on trakt

### ISSUE THREAD

**Issue by UweTrottmann** [UweTrottmann/SeriesGuide#468]
_Reported via email_

For Naruto,
- set episode x of season 1 watched >> sets episode x of season 2 on trakt
- set episode x of season 2 watched >> error

https://trakt.tv/shows/naruto

**Comment by bikashdora** [comment]
Its not an issue right now.

**Comment by UweTrottmann** [comment]
Checked, and you're right. Thanks! Closing.
Am 16.12.2015 12:37 schrieb "bikashdora" <notifications@github.com>:
