### ISSUE TITLE
Questions about TheTVDB direct integration - without trakt.tv login

### ISSUE THREAD

**Issue by RoundSparrow** [UweTrottmann/SeriesGuide#469]
Hi.  Developer question: I see from the changelog that it used to be possible to directly search TheTVDB - but this was disabled.

I'm curious about ideas and thoughts on using SeriesGuide without trakt.tv login.  There is another open source Apache 2.0 app out there for Android that has direct integration with TheTVDB - https://github.com/tarzasai/Uoccin

Is there any reason to be against having a mode that is pure TheTVDB?

**Comment by UweTrottmann** [comment]
You can still use SeriesGuide without logging into trakt. Most of the show data is still coming from TheTVDB, I just switched over to trakt for search (which is better) and getting some additional info (release country, time zone and time).

Does this answer your question?
