### ISSUE TITLE
Multiple episodes at the same time: incorrect sort order on widget

### ISSUE THREAD

**Issue by UweTrottmann** [UweTrottmann/SeriesGuide#471]
*Reported by email*

Still need to confirm this (last time I checked it worked).

If e.g. a Netflix show releases many episodes at once, a widget showing recent episodes orders them incorrectly.

**Comment by JakeWharton** [comment]
Last time I checked (Orange is the New Black S3, House of Cards S3) this
worked as well.

**Comment by UweTrottmann** [comment]
Yeap, works correctly. Closing as invalid.
