### ISSUE TITLE
Manage watched movies too!

### ISSUE THREAD

**Issue by btwael** [UweTrottmann/SeriesGuide#479]
I know the name application is "SeriesGuide", but it's the best one for series, so I hope if you add to managing movies (watched movies, statistics...)

**Comment by JakeWharton** [comment]
It already does this. Select "Movies" from the navigation drawer.

**Comment by UweTrottmann** [comment]
@btwael Is what @JakeWharton said what you were looking for?

If this is about support for displaying your watched movies, you can vote for the suggestion at seriesguide.uservoice.com.
