### ISSUE TITLE
Episodes not watched is incorrect

### ISSUE THREAD

**Issue by daibhid** [UweTrottmann/SeriesGuide#482]
The number of unwatched episodes for one season of my shows does not match number of episodes I have not currently watched.

Attached a screenshot showing the issue:

![Screenshot showing issue](http://i.imgur.com/I2EaNWO.jpg)

SeriesGuide is reporting that I have 26 unwatched episodes, but the count in the top right shows I have seen 144 of 308 episodes (this number is correct, the 26 unwatched episodes is incorrect).

**Comment by UweTrottmann** [comment]
This behavior is intended. The counter on the right counts any episode. While the text below only takes into account episodes that have a release date and have already been released.

**Comment by daibhid** [comment]
Excellent, thanks, I see the issue with the series information on thetvdb.
