### ISSUE TITLE
Next episode is always sorting by release date

### ISSUE THREAD

**Issue by odwk** [UweTrottmann/SeriesGuide#483]
Here's an example with the show Wonderfalls, but this works with any show that aired in the 'wrong' order. 

1. Set 1x05 Crime Dog (DVD 5.0, aired 23/07) and all older episodes as watched
2. Next Episode is now 1x07 Muffin Buffalo (DVD 6.0, aired 23/07). It jumped 1x06 Barrel Bear (DVD 7.0, aired 27/10)
3. After setting 1x07 as watched, Next Episode is now 1x11 Cocktail Bunny (DVD 11.0, aired 25/07)

Is there a way to make Next Episode follow the sorting order selected in the episode list(if we're watching the show on Netflix, DVD or any other source that isn't TV)? Sometimes setting a special episode as watched makes SeriesGuide jump whole seasons, because it aired in the middle of the show.

**Comment by UweTrottmann** [comment]
This is currently not possible. This is pretty much #169, so closing this one.
