### ISSUE TITLE
List widget not updating

### ISSUE THREAD

**Issue by UweTrottmann** [UweTrottmann/SeriesGuide#484]
_Status: can not reproduce, though observed on own device once_

Example: "Upcoming" widget, an episode shows as tomorrow though the day is already today. Note that marking an episode as watched updates it.﻿
- It's maybe not Android 6 (one user on 5.1.1/LG V10)
- 2x 6.0/LG V4, 5.1.1/LG V10, my own 6.0/Moto X Play
- Reports since about version 28, 29-beta2 (which trigger widget updates also from within the app, not just through the update alarm)

**Possible causes**
- Briefly caught `ListWidgetProvider` crashing, maybe this is a cause?
  Trying with context used to update widget set to app context. **released with 29-beta3**
- App Standby not the issue: app can't enter app standby if widget added to home screen (tested on emulator and device).
- Doze mode? In theory `setRepeating` alarm should be delivered after leaving doze mode, works on my device. **Causes multiple alarms to be delivered at once, switched to using single alarm and re-setting it (18e7073e8c71b366345a75eabb1442d5c7c6a4b6, v40-beta6)**

**Links**
- [Community feedback](https://plus.google.com/+SeriesGuideApp/posts/FgTXrFNL2eC)
- http://developer.android.com/training/monitoring-device-state/doze-standby.html#testing_doze_and_app_standby

**Comment by UweTrottmann** [comment]
This seems to be an issue with Nova launcher. From time to time the widget stops updating and needs to be removed and re-added. As all code looks fine, treating this as a launcher issue for now.

**Comment by Aerozolic** [comment]
I'm using OnePlus Launcher and I also have issues with widget not updating.
I received a notification about new released episode hours ago but the widget doesn't show it. Opening SeriesGuide doesn't help. After I opened widget settings and closed it the newly released episode showed up.

**Comment by UweTrottmann** [comment]
@Aerozolic Thanks. Though still have no pointers on what SeriesGuide is doing wrong here. Does the OnePlus have the stock-Android Optimize battery life setting for apps? Maybe try to exclude SeriesGuide from the optimizations to see if that helps.

**Comment by Aerozolic** [comment]
@UweTrottmann I set the app to "Don't optimise" and it didn't fix the issue unfortunately. Still had to open widget settings and tap the "V" to get the latest episodes to show up.

**Comment by Aerozolic** [comment]
Same issue on Pie. SeriesGuide version V47-beta3

**Comment by UweTrottmann** [comment]
There have not been any reports for a while. Issues seem mostly related to overeager power management on devices.
https://dontkillmyapp.com/
