### ISSUE TITLE
Add option to open added show from add dialog

### ISSUE THREAD

**Issue by UweTrottmann** [UweTrottmann/SeriesGuide#485]
[Suggested on G+](https://plus.google.com/108096276962711982950/posts/bjdQcwPMKns)

**Comment by joe1616** [comment]
Enhancement could you explain that to .end cause I signed up ato git hub I couldn't figure it out .. I even ask help I was why are here then ..answer would  be gota somewhere. . Sorry and the long text but I'm profiling myself to u or who ever is watching my progress or mistakes .. I'm all day I'll try to get back asap.. joe
