### ISSUE TITLE
Seriesguide Cloud API

### ISSUE THREAD

**Issue by ssc-hrep3** [UweTrottmann/SeriesGuide#488]
Is there a Seriesguide Cloud API? This would be a nice extension of the great service of seriesguide. One example for a usage of these data could be, similar to a rss news feed, on a simple personal information website.

**Comment by UweTrottmann** [comment]
The current Cloud API is restricted to the SeriesGuide clients, so yes/no. I am not ready to handle a public API at this point (would require additional tools to handle abuse, let alone funds and time).

**Comment by UweTrottmann** [comment]
Probably better to submit this to https://seriesguide.uservoice.com. Closing this.
