### ISSUE TITLE
Back button bug in recent

### ISSUE THREAD

**Issue by SubhrajyotiSen** [UweTrottmann/SeriesGuide#489]
Steps to recreate the bug
1. Go to RECENT tab
2. Click on any episode
3. Press back button in toolbar
It goes to episode list instead of going back to RECENT

**Comment by UweTrottmann** [comment]
The arrow button in the toolbar is the up button. To go back use the back button in the navigation bar next to the home button. Or the physical back button on your device. See https://developer.android.com/training/design-navigation/ancestral-temporal.html
