### ISSUE TITLE
Faulty animation direction when leaving season and episode view via up navigation

### ISSUE THREAD

**Issue by Jakob-Ruf** [UweTrottmann/SeriesGuide#490]
Animation is shown from right to left when leaving the view for a single season or episode via the up navigation in the upper left corner despite the logical direction being left to right. Leaving a tv show via this button shows the correct animation direction. 
Issue is not present when navigating back with the back button in navigation bar.

**Comment by UweTrottmann** [comment]
SeriesGuide is using the default platform (Android) animation for that. What version of Android are you using? Are you using a custom version of Android like CyanogenMod?

**Comment by Jakob-Ruf** [comment]
I'm using MIUI. Might very well be that's their issue. Oh well, another reason to switch to CM or something else
