### ISSUE TITLE
Trakt syncing (with large history?) is slow, disruptive, can cause data loss

### ISSUE THREAD

**Issue by ferdnyc** [UweTrottmann/SeriesGuide#491]
I really like the _idea_ of trakt syncing in SeriesGuide. While SeriesGuide is my preferred tool for organizing my viewing, mirroring that history to an online, shared database with social features has a certain appeal.

However, the reality of the current trakt syncing feature — as it exists in SG v.30.0.1(Database v38) — falls somewhat short of that ideal, and is making me consider disabling the trakt syncing just to restore some usability to SeriesGuide. Here's my typical SeriesGuide experience, with AutoUpdate enabled and SeriesGuide connected to trakt (only, not Cloud):

1. Launch the SeriesGuide app, which usually takes me to Recent as that's the tab I was last viewing.
2. The spinner at the top of the tab begins twirling as SeriesGuide starts syncing with trakt.
3. Various shows begin transiently appearing in the list, as SeriesGuide "resets" their watched status before applying the state downloaded from trakt. (This is bug #487)
4. If I attempt to mark any episodes (of any show) as Watched during the syncing process, those watched flags will more often than not be lost by SeriesGuide when it finishes syncing. 
  - (This may relate to bug #458 — @pironic writes "Occasionally I find that under some conditions outside of the SeriesGuide pervue, shows and movies are scrobbled twice.", but I find that most of my duplicate activity is caused _by_ SeriesGuide, when it loses Watched flags and I re-apply them, only to later find out that I've created duplicates.)
5. _Several **minutes**_ after syncing starts (this is no exaggeration — the syncing spinner can last anywhere from 45 seconds to 2, 3+ minutes), the update completes and I am able to make changes in SeriesGuide without them being lost.

I realize that what SeriesGuide can do in syncing with trakt is constrained by the trakt API, and that ideal efficiency may not be possible given those constraints. But I feel like _something_ at least needs to be done to make the syncing (a) more asynchronous and (b) less disruptive, so that SeriesGuide can be used while it's going on. The situation in bug #487 — where SeriesGuide manipulates the live datastore during the syncing process, removing and reapplying the entire Watched history for a show instead of simply making updates ­— feels like a prime candidate for refactoring and improvement.

As some data points on my situation, SeriesGuide is running on a Samsung Galaxy S4, not exactly a slow or resource-starved device. (And I'm running SlimKat 9.0, a CyanoGen-based Android 4.4.4 — not Samsung's dog-slow stock OS.) It connects to the internet over Sprint's 4G LTE network in New York City, which typically gives me SpeedTest numbers of 6 - 12 Mbps down, 4 - 6 Mbps up. In every sense, performance is as good as can reasonably be expected.

To give you an idea of my _datastore_, this is what SeriesGuide is working with:

![screenshot_2016-05-20-08-31-35](https://cloud.githubusercontent.com/assets/538020/15429795/83abdf02-1e70-11e6-970a-c6fcd62f6f65.png)

So, I'm _far_ from a light user. It's entirely possible that I simply have too much data in SeriesGuide, and syncing it all to trakt is just too intensive a process. However, most of those shows are fully watched and Hidden, simply there for historical reasons. There's no reason to expect that they'd be receiving updates. If necessary I can delete the historical data from SeriesGuide, though it would be preferable if that info could simply be excluded from the syncing process in some way, rather than having to be discarded.

It's also possible that having active shows on my list like Saturday Night Live (41 seasons / 810 episodes and counting) and The Simpsons (27 seasons / 602 episodes and counting) makes the syncing process unduly heavy. But, short of canceling those shows, I'm not sure what I can really do about that, so if that is indeed a problem then it would appear to be another way in which the syncing process is ripe for improvement. (I haven't even considered adding really high-volume shows like The Daily Show to SeriesGuide, even though I do watch it regularly.)

SeriesGuide is a really great tool, and the trakt integration, while intriguing, would be a wonderful feature if only it didn't interfere so greatly with the app's performance and utility.

**Comment by ferdnyc** [comment]
Just to add a little more data to this, I turned off AutoUpdate in the preferences and that seems to have alleviated a lot of the problems, most especially the endless spinner-wait delays on (nearly every) app launch. It's not real clear to me exactly what I'm giving up in doing so, but it does seem to help. So, the slowness/blocking issues may be more about the AutoUpdate process, than inherent to the trakt syncing itself.

**Comment by UweTrottmann** [comment]
Thanks for this. Yes, there is room for improvement. 

And trakt sync is part of the auto update process. If you turn it off you can manually sync via the menu under Advanced.

**Comment by ferdnyc** [comment]
Thanks, that's good to know.

So, if I'm understanding SeriesGuide's trakt integration correctly, with Auto Update disabled it will still _send_ watches to trakt, just not sync back any changes made on the trakt end... correct? (Effectively, the trakt syncing will I guess be one-way?) That seems like a workable compromise, since the SeriesGuide->trakt pipe is pretty efficient and non-disruptive.

(Also, all of my trakt activity comes from SeriesGuide, generally, so a one-way pipe is sufficient for my personal needs. There's nothing it really needs to be pulling back in from trakt.)

Switching off Auto Update entirely feels a bit drastic, though, since it would be nice to still have the calendar and status information automatically kept current. As much as I hate to even suggest it, perhaps it would be helpful if [auto] trakt syncing could be toggled separately from the rest of the Auto Update process?

**Comment by UweTrottmann** [comment]
Improved speed for trakt watched and collected episodes sync with `31-beta3`.

**Comment by ferdnyc** [comment]
I just wanted to mention that I've been running v32-beta3 for a week or two now, and the difference is really striking. Even with Auto Update re-enabled, startup spinning/waiting seems to have basically disappeared. It's like night and day. Many thanks!

**Comment by UweTrottmann** [comment]
Great to hear, thanks for sharing!


Am 17. August 2016 17:33:42 schrieb Frank Dana <notifications@github.com>:
