### ISSUE TITLE
Gradle problem in Android Studio 2.1

### ISSUE THREAD

**Issue by paveltech** [UweTrottmann/SeriesGuide#492]
I want to import this project into my android-studio so that i download hole project and try to open it from android-studio.After that it shows some error in api gradle error is
 "Error:(84, 0) No such property: ossrhUsername for class: org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer
<a href="openFile:/home/lolipop/Downloads/SeriesGuide-dev/api/build.gradle">Open File</a>"

I am confused about really i need api folder in my project or which folder i need to import this project.

**Comment by UweTrottmann** [comment]
Have a look at 
https://github.com/UweTrottmann/SeriesGuide/blob/dev/CONTRIBUTING.md#setup

Uwe Trottmann
uwetrottmann.com



Am 25. Juni 2016 09:45:53 schrieb "Md.Masud Parvez" <notifications@github.com>:

**Comment by paveltech** [comment]
thnx i am watching it

**Comment by paveltech** [comment]
I can't understand what are you saying in Setup section.
I just download the folder then open it from android-studio is it ok? if not then what should i do to import it.

**Comment by UweTrottmann** [comment]
If you have not solved the issue, yet: you need to create a `gradle.properties` and `fabric.properties` file to build the project. I made the [setup instructions](https://github.com/UweTrottmann/SeriesGuide/blob/dev/CONTRIBUTING.md#setup) more clear about this.

And yes, you should be able to just import as a new project using the `settings.gradle` file.
