### ISSUE TITLE
Crashlytics Developer Tools error.

### ISSUE THREAD

**Issue by paveltech** [UweTrottmann/SeriesGuide#493]
Finally i can import it into android-studio.After sync gradle it show one error that is 

Error:Execution failed for task ':SeriesGuide:fabricGenerateResourcesAmazonDebug'.
> Crashlytics Developer Tools error.

How i can solve it.

**Comment by UweTrottmann** [comment]
As said in #492 you have to also add a `fabric.properties` file to build the project. I made the [setup instructions](https://github.com/UweTrottmann/SeriesGuide/blob/dev/CONTRIBUTING.md#setup) more clear about this.
