### ISSUE TITLE
[API] Getting TV show release year (or release date)

### ISSUE THREAD

**Issue by NitroXenon** [UweTrottmann/SeriesGuide#494]
So there are some TV shows with the same name, e.g. The Flash 2014 and The Flash 1990. I think it's more convenient if we (extension devs) can get the release year or the release date of the show through ```com.battlelancer.seriesguide.api.Episode```. Really hope you can implement it.

**Comment by UweTrottmann** [comment]
Should be possible. Probably will send the first release time as set on TVDb. Thanks for the suggestion!

**Comment by NitroXenon** [comment]
Is "first release time" means "first air date"? Really hope this will be in the next release because my extension really needs this info to get accurate result.

**Comment by UweTrottmann** [comment]
This will ship with the upcoming API `1.3.0` release. SeriesGuide will support this with upcoming `33-beta1`.

**Comment by NitroXenon** [comment]
Thanks 👍

**Comment by UweTrottmann** [comment]
Additional details about the changes [on the wiki](https://github.com/UweTrottmann/SeriesGuide/wiki/Extension-API).

**Comment by NitroXenon** [comment]
Thanks. Love the new movies api support. :D
