### ISSUE TITLE
Feature Suggestion: "Undo" for Recent/Upcoming list checkins

### ISSUE THREAD

**Issue by ferdnyc** [UweTrottmann/SeriesGuide#495]
Occasionally while scrolling the Recent list, I accidentally tap a checkmark next to one of the entries, marking something as Watched that I didn't intend. Since the entry immediately disappears, usually before I can notice what it was, I'm left with only the "XxYY Seen. Sent to trakt" message at the bottom of the screen as a hint as to what I just accidentally removed from the list, so that I can hunt it down and un-mark it. Sometimes that's easy, as there are other episodes of the same show nearby and the "hole" is obvious. Sometimes it's far from obvious, and requires substantial digging.

It'd be handy if the "checked-in" message stuck around slightly _longer_ than it does currently, and either provided an "Undo" function directly, or (failing that) was tappable to navigate to the episode in question, so that it could be unmarked. (Currently, attempting to tap on the message just selects whatever list entry is below it.)

This is in line with, e.g. GMail's list features, where immediately after an action is taken, the success message includes an Undo link in case the action was made in error.

![screenshot from 2016-08-29 22-55-29](https://cloud.githubusercontent.com/assets/538020/18074685/66cf9506-6e3c-11e6-923c-7cd07271550b.png)

**Comment by ferdnyc** [comment]
(And I realized after posting this that the easiest way to figure out what I just accidentally marked would be to visit the "Now" tab, which includes a list of recently-watched items. Still, the suggestion about direct Undo from the list view stands, as it would be an additional convenience.)

**Comment by UweTrottmann** [comment]
Alright, probably best to [vote for this idea](https://seriesguide.uservoice.com/forums/189742-ideas-and-suggestions/suggestions/5661611-add-gmail-like-undo-button-when-marking-an-episode) or create a new one.

**Comment by ferdnyc** [comment]
Aha! Didn't realize that uservoice space was there. Done and done, thanks!
