### ISSUE TITLE
Missing Show poster even though tvdb and trakt have one

### ISSUE THREAD

**Issue by Kiina** [UweTrottmann/SeriesGuide#496]
So I noticed that some shows are missing the Poster/Cover in the overview. I checked both tvdb and trakt (because I am not sure from which of the places the Information gets pulled) and they both had images for the Show. I even tried this on multiple devices with and without trakt login.

Example Shows:

https://trakt.tv/shows/infinite-challenge
http://thetvdb.com/?tab=series&id=284209

https://trakt.tv/shows/god-s-quiz
https://thetvdb.com/?id=270695&tab=series

The strange thing is, in the overview to add the Show to your list there is an image for both Shows. But if you add them to your list it disappears.

**Comment by UweTrottmann** [comment]
Can you try clearing the cache for SeriesGuide? See Settings > Advanced > Clear image cache, it points you to the Android Settings screen where you can clear the cache.

**Comment by Kiina** [comment]
Yeah, the image for the shows still dont work. Like I said I tried it on different devices so this should be reproducible. Try adding the show and you will probably encounter the same thing.

Another thing I noticed is that in the "Add Show" overview there is an image, but if you click the show in the pop up there is none.

**Comment by UweTrottmann** [comment]
Sorry for the late response: all the posters for those two shows are tagged as Korean (한국어). So either:
- Change the language to Korean for those shows (from Show tab after tapping on a show)
- Create and upload an English language poster to TheTVDB (or ask someone to use theirs).

**Comment by Kiina** [comment]
Okay that seems to work for me

Don't know how much of an edge case this is, but wouldn't it be better to pull information from prefered language > show language > any language? Because a poster in a another language is better then no poster. Same with other information.

**Comment by UweTrottmann** [comment]
SeriesGuide will use the language that you added the show in. For example, if you search for Korean shows, SeriesGuide will add that show with the language set to Korean.
