### ISSUE TITLE
Estimated runtime resets when you lock the screen

### ISSUE THREAD

**Issue by Kiina** [UweTrottmann/SeriesGuide#503]
Like outlined in this issue [here](https://github.com/UweTrottmann/SeriesGuide/issues/402) the calculation of the estimated runtime is slow. The problem is you have to keep the device screen on while calculating else it will reset and start over. Which is kinda bad if it takes 15 seconds or more to calculate. Same thing if it calculated and you switch of the screen.

**Comment by UweTrottmann** [comment]
You are right, looks like I overlooked this. Thanks!
