### ISSUE TITLE
Make SeriesGuide Settings compliant with DPI changes

### ISSUE THREAD

**Issue by KamranMackey** [UweTrottmann/SeriesGuide#508]
With my DPI of 520 on the LG G3, (running LineageOS), the settings activity of SeriesGuide doesn't fit the entire area. Its like squished together and centered, which makes things really weird. This doesn't happen with other areas of the app. I've attached a screenshot just in case it'll help.

Android version: 7.1.1 (LineageOS 14.1)
Model: LG G3 (d852)
SeriesGuide version: 35

![image](https://cloud.githubusercontent.com/assets/1617100/22851537/33eef424-efe2-11e6-8d97-677b3afbcb23.png)

**Comment by UweTrottmann** [comment]
This is on purpose: once the screen is wide enough settings are centered. This is to make settings not look too bad on wide screens (try rotating your screen). The solution would be to re-implement PreferenceFragment, but this is very low priority right now.
