### ISSUE TITLE
Cover images for some shows are not shown

### ISSUE THREAD

**Issue by marco-c** [UweTrottmann/SeriesGuide#509]
There are some shows for which SeriesGuide intermittently fails to show the cover image.

If I open the series and go to the description tab, the cover is still not shown. If I press on the rectangle where the cover should be, I see the cover.

Open series list (both first time and following times):
![screenshot_20170216-144426](https://cloud.githubusercontent.com/assets/1616846/23025679/a7d239fa-f456-11e6-87c8-4ab1ad15edcd.png)

After ~one second:
![screenshot_20170216-144418](https://cloud.githubusercontent.com/assets/1616846/23025715/c3c9dcc6-f456-11e6-9ae1-4ff8c7486015.png)

Open series details page:
![screenshot_20170216-144408](https://cloud.githubusercontent.com/assets/1616846/23025737/d2ed78ca-f456-11e6-9021-37c9172e3d39.png)

Open image from the series details page:
![screenshot_20170216-144404](https://cloud.githubusercontent.com/assets/1616846/23025754/dbf3f214-f456-11e6-9fa0-a5c9e1055656.png)

**Comment by UweTrottmann** [comment]
Check https://seriesgui.de/help#images Probably a cache issue.



Am 16. Februar 2017 15:47:54 schrieb Marco <notifications@github.com>:

**Comment by marco-c** [comment]
Yes, it's working now.
