### ISSUE TITLE
support multiple plays

### ISSUE THREAD

**Issue by Hauwertlhaufn** [UweTrottmann/SeriesGuide#511]
It would be nice if SeriesGuide would support multiple plays, like trakt does it. For example with a long press on seen to add another play. Also a number of the plays next to the tick wuld be nice.

**Comment by UweTrottmann** [comment]
I suggest you vote for [this suggestion](https://seriesguide.uservoice.com/forums/189742-ideas-and-suggestions/suggestions/11734887-multiple-watching-and-watch-date).

Closing as this is not a bug.
