### ISSUE TITLE
Option to view show details in some of the screens

### ISSUE THREAD

**Issue by nitrobg** [UweTrottmann/SeriesGuide#515]
I'm referring to the small popup that appears when the user clicks on a show in Add Show, Recommended and Watchlist sections of the Search screen - there should be either a link or a button that lets the user view the show's details without adding it to a list.

**Comment by UweTrottmann** [comment]
Thanks for the suggestion. It is currently easy enough to just add the show, wait, open it right from the search results. Then remove it again from the overview more options.
