### ISSUE TITLE
Bad error reporting when show is not up2date on trakt

### ISSUE THREAD

**Issue by Kiina** [UweTrottmann/SeriesGuide#519]
So I wanted to set an Episode to watched and got the following error: "Could not talk to trakt. Try again later." I tried again later and still the same. Then I noticed the Episode is still missing in the trakt Database and is only on tvdb. Maybe there should be error reporting that accounts for this so trakt VIP users can go on the site and refresh the data.

**Comment by UweTrottmann** [comment]
Thanks, this is already tracked with #454.
