### ISSUE TITLE
Local search only works with exact title

### ISSUE THREAD

**Issue by Kiina** [UweTrottmann/SeriesGuide#520]
Let's say I want to find the Show `Mr Robot`. I search `Mr Robot` and nothing shows up. That is because it has a little `.` in the Name. If you search `Mr. Robot` it shows up. It would be great if it just showed everything with `Mr` and `Robot` in the Name.

Also the Korean search has this problem with Syllable Blocks. It only searches for completed syllable blocks. So if you search for `무한도전` you won't find anything with `무하` until you add the little nieun (ㄴ). But maybe that's an edge case for most users.

**Comment by UweTrottmann** [comment]
Show search in SeriesGuide is provided by TheTVDB (except for English, that uses the search service provided by trakt.tv). They already know that they expose an inferior search to apps. There is not much I can do as running my own search service seems overkill.

**Comment by Kiina** [comment]
The local search for shows in my list? Because the search for new shows works okay. Which is strange...

**Comment by UweTrottmann** [comment]
Oh, sorry. I assumed you meant the search when adding a new show. Will have a look, thanks!

**Comment by UweTrottmann** [comment]
Not sure how to get around this as SQLite FTS does not support fuzzy searching or multiple placeholders.

**Comment by thouseef** [comment]
Why don't we tokenise and search using 'OR' ? 
I just forked this repo. If I get time, I'll try and implement a solution.
