### ISSUE TITLE
X Pass: No such app found.

### ISSUE THREAD

**Issue by nloomans** [UweTrottmann/SeriesGuide#521]
Hey, when I click on the "GET X PASS" button an app (presumably Google Play) is opened and immediately closed leaving behind a toast that says "No such app found". I live in the Netherlands if that is of any relevance.

**Comment by UweTrottmann** [comment]
Can you check if opening https://play.google.com/store/apps/details?id=com.battlelancer.seriesguide.x directly works? What device model and version of Android is this on?

**Comment by nloomans** [comment]
That link does not work. I'm using a Nexus 5X on Android O

**Comment by UweTrottmann** [comment]
Could not reproduce, tested on Android 7.0 (N) and Android 8.0 (O). So this either is a configuration issue or a bug in the Play Store version on your device (unlikely as others would have reported this).

As opening the link directly also does not work, I assume you are either using a restricted profile that blocks your web browser. Or an app is hijacking all web address (URL) view intents. Check **Settings > Apps & notifications > Advanced > Default apps** that there is a valid **Browser app** set.

**Comment by UweTrottmann** [comment]
No response, closing.

**Comment by nloomans** [comment]
Sorry, forgot about this. The issue was indeed on my side
