### ISSUE TITLE
Provide an option to export / import lists of TV Show episodes

### ISSUE THREAD

**Issue by icyflame** [UweTrottmann/SeriesGuide#523]
Since lists aren't synced to Trakt, it would be a good idea to provide users with the option to export their lists to a file ([OPML](https://en.wikipedia.org/wiki/OPML), if that is the right format) and import it into the app at a later point in time or import on another phone.

(This is a feature request, I am not familiar with the stack that this project uses / how the episodes and lists are stored, so I am sorry if I am making a basic mistake in the understanding. That said, I am familiar with Android and I will look at the code and find the right portions.)

@UweTrottmann Is this a feature that you would be interested in?

**Comment by UweTrottmann** [comment]
You can already export to JSON format using the backup and restore tool in settings. For details about the format see https://github.com/UweTrottmann/SeriesGuide/wiki/JSON-export-format
