### ISSUE TITLE
Add support for adaptive icons

### ISSUE THREAD

**Issue by pwd-github** [UweTrottmann/SeriesGuide#525]
https://medium.com/google-design/understanding-android-adaptive-icons-cee8a9de93e2#9f84

**Comment by JakeWharton** [comment]
They already are adaptive.

**Comment by pwd-github** [comment]
It's working for circles, but not for other shapes.

**Comment by JakeWharton** [comment]
They work fine too

![screenshot_20171030-212751](https://user-images.githubusercontent.com/66577/32203394-6e7f9f76-bdb9-11e7-84ca-657b32138391.png)
![screenshot_20171030-212804](https://user-images.githubusercontent.com/66577/32203392-6b40379e-bdb9-11e7-9a4e-da43a2543fd3.png)

**Comment by UweTrottmann** [comment]
@pwd-github If you are not using the Pixel launcher (on Google Pixel devices), this is likely a problem with your launcher or device and not SeriesGuide. 

So, for a proper issue report: what device and version of Android is this on, what launcher are you using?

@JakeWharton Thanks!

**Comment by pwd-github** [comment]
I am indeed using a third party launcher in Nova.

**Comment by UweTrottmann** [comment]
Alright, closing then.

**Comment by pwd-github** [comment]
This was fixed with the last update.
