### ISSUE TITLE
Series does show wrong language

### ISSUE THREAD

**Issue by MasterOfBytes** [UweTrottmann/SeriesGuide#526]
I added "Tatort" to my Series. But it shows "Scene of Crime" and that there is no description in English. But the language in the settings is German. And there are german Descriptions in TheTVDB
Other series working fine.

Samsung Galaxy S7 Edge
![screenshot_20171101-183055](https://user-images.githubusercontent.com/13133095/32332737-8a85e6c4-bfe6-11e7-8fb5-511331c7d9ce.png)

**Comment by UweTrottmann** [comment]
Look in the 'SERIE' tab and change the language by tapping the globe button. Shows are added in the language you searched for them (there also is a globe icon next to the search box). 
The language in settings is only used in some corner cases where SeriesGuide can't figure out the desired language.

**Comment by MasterOfBytes** [comment]
Oh.
That's not so really viewable, but ya. It works. Sorry for the "Bug".
