### ISSUE TITLE
Sorting lists not working

### ISSUE THREAD

**Issue by corneil** [UweTrottmann/SeriesGuide#531]
No matter which option I choose the sorting seems to be random.
It worked in the past and I upgraded to new device recently now I cannot get the order I want.
I want to see the shows in order of next episode to watch with the shows that are Ended or Continuing at the bottom of the list.

Sorting the Shows tab seems to work but Lists behave different.

**Comment by UweTrottmann** [comment]
Can you give a specific example, possibly a screenshot?

Note that lists can also contain single seasons and episodes in addition to shows. Maybe that is throwing you off.

**Comment by UweTrottmann** [comment]
No response, closing.
