### ISSUE TITLE
Locale aware ordering of titles

### ISSUE THREAD

**Issue by onlined** [UweTrottmann/SeriesGuide#534]
Sorting of titles should be locale aware. Now, it's only case insensitive, as you can see:
https://github.com/UweTrottmann/SeriesGuide/blob/78ecb95020224f0d66b1c8991e67dad2b74a92cd/app/src/main/java/com/battlelancer/seriesguide/provider/SeriesGuideContract.java#L659
https://github.com/UweTrottmann/SeriesGuide/blob/78ecb95020224f0d66b1c8991e67dad2b74a92cd/app/src/main/java/com/battlelancer/seriesguide/provider/SeriesGuideContract.java#L1040
I searched for `NOCASE LOCALIZED` (both case insensitive and locale aware), but it is not valid in Android SQLite. So I think that storing lowercase titles and ordering by them is the best solution, but I am open to comments and ideas.

**Comment by UweTrottmann** [comment]
[Though even when using `LOCALIZED`](https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html), it "changes with the system's current locale". So this will not work if shows use titles in different languages, no?

**Comment by onlined** [comment]
Actually, it will be better than now, I think. As a Turkish person, I expect that the letter `Ç` would be between `C` and `D`. I think most of the non-native English speakers has an intiution like mine.
