### ISSUE TITLE
Fall back to alternative language for show titles and description as well

### ISSUE THREAD

**Issue by JoeyCorleone** [UweTrottmann/SeriesGuide#537]
Preferred content language: English
Alternative language: Deutsch
SeriesGuide v42.2 (Database v42)
connected to trakt.tv

I search for "Familie Braun" or "Charité" in the Discover tab and add the show.

Result: the series name is shown as "Not translated"

Expected result: "Familie Braun" or "Charité" as shown in the Discover tab

**Comment by UweTrottmann** [comment]
The alternative language is currently only used for episode descriptions. I will look into expanding it to episode titles as well as show titles and descriptions.

For now: when adding a show make sure to select "Deutsch" with the globe icon next to the search bar. You can also change the language of a show after adding it above the show description.

**Comment by JoeyCorleone** [comment]
> For now: when adding a show make sure to select "Deutsch" with the globe icon next to the search bar. You can also change the language of a show after adding it above the show description.

Thanks for the hint! :)

**Comment by UweTrottmann** [comment]
Starting with SeriesGuide 45 the fallback language for shows (English by default) is used to get show info not available in the desired language.
