### ISSUE TITLE
Movie disc releases not updating

### ISSUE THREAD

**Issue by gravelga** [UweTrottmann/SeriesGuide#539]
I changed my cellphone from a Nexus 4 to a Samsung A5. On the latter, I am not able to update the "Disc releases" and have been stuck with one movie.

On my previous phone, I do not have this issue.
Updating manually (by wiping screen down) also does not work.

[Imgur](https://imgur.com/a/PbOw7Mq)

**Comment by UweTrottmann** [comment]
Check the country and language selection using the globe symbol in the top 
right.

Am 23. Juni 2018 06:28:13 schrieb gravelga <notifications@github.com>:

**Comment by gravelga** [comment]
The country was set to Canada. I changed it to Unites States and everything works as intended.

Thanks for the incredibly fast response and great job for the app itself.
