### ISSUE TITLE
Update TVDB links for new site

### ISSUE THREAD

**Issue by UweTrottmann** [UweTrottmann/SeriesGuide#545]
Old format:
The Joel McHale Show with Joel McHale - 1x12 Folge 12 https://thetvdb.com/?tab=episode&seriesid=341483&seasonid=747980&id=6617433&lid=7

New format:
https://www.thetvdb.com/series/341483/episodes/6617433

- [x] Wait for response: https://forums.thetvdb.com/viewtopic.php?f=17&t=47708
- [x] Use new link format

**Comment by UweTrottmann** [comment]
No clear support for linking using the TVDB id. Slugs are used if one exists. But slugs do not appear to be available through the API.

There is a referrer method which seems to accept a TVDB id.

Using the old links seems a better solution for now (especially as they are used for sharing).

**Comment by UweTrottmann** [comment]
The API now returns `slug` for `Series`. Update `thetvdb-java`, then use this.

**Comment by eWU6yS6F** [comment]
Was it intended behaviour that the old links no longer suggest adding the show? I use a couple of sites that link to tvdb using the old format, and it would be nice to share the link to seriesguide to quickly add it, but it isn't recognised.

**Comment by UweTrottmann** [comment]
Yes, thanks for the heads up.

- [ ] I will look at adding support for the old link format, again.
