### ISSUE TITLE
No language selection when adding shows from lists

### ISSUE THREAD

**Issue by reboot** [UweTrottmann/SeriesGuide#570]
When you add a show from the predefined lists on the discover tab, like 'popular', 'watched' or 'watchlist' you have no choice which language will be used for the show. It will always use the default language regardless of what is selected using the globe icon near the search field.

**Comment by UweTrottmann** [comment]
Thanks! With the next update SeriesGuide will use the search language, or if there "Any language" is selected, your fallback language.
