### ISSUE TITLE
an option to change the app language

### ISSUE THREAD

**Issue by azumukupoe** [UweTrottmann/SeriesGuide#571]
I've read [this](https://seriesgui.de/help#language) but the translation isn't good enough in my opinion.

**Comment by UweTrottmann** [comment]
What translation/language is affected?

Also, if you have the time, help out proof reading or suggesting better translations: https://crowdin.com/project/seriesguide-translations/invite

**Comment by azumukupoe** [comment]
I feel the Japanese translation is done by google translate. Unfortunately, I don't have enough time to take care of community translations. Could you consider adding the option?

**Comment by UweTrottmann** [comment]
Thanks for letting me know. I did some point checks on the Japanese translation, mostly done by user naofum (go to https://crowdin.com/project/seriesguide-translations/activity_stream and filter by Japanese), but it does not appear that most translations are done by a translation tool.

I could consider removing the complete translation, but that seems to be overkill.

I do not want to add a language option. This would require replacing built-in Android language support, which I rather not do (time consuming, error prone).

I invite anyone with the time to vote on or suggest better translations for Japanese at https://crowdin.com/project/seriesguide-translations/ja#
