### ISSUE TITLE
Update icons to version MD2

### ISSUE THREAD

**Issue by igor-dyatlov** [UweTrottmann/SeriesGuide#594]
I propose to update the form of the icon to version md2. With rounded edges.
Example:
![round_done_black_48](https://user-images.githubusercontent.com/15961107/49673015-1c27e500-fa7e-11e8-80a2-4f64cbf530a0.png)

**Comment by igor-dyatlov** [comment]
https://material.io/tools/icons/?icon=done&style=round

**Comment by UweTrottmann** [comment]
Nah, already changed to the outline versions recently.
