### ISSUE TITLE
Remove trakt recommendations code if feedback is positive (or none)

### ISSUE THREAD

**Issue by UweTrottmann** [UweTrottmann/SeriesGuide#607]
Experimentally removed link to trakt recommendations from the discover screen. They have never been really useful, so hide them.

If there is no feedback about the removal, remove all of the associated code as well.

**Comment by danopz** [comment]
I'm just curious why exactly do you think they have never been useful?

**Comment by UweTrottmann** [comment]
@danopz Over the years I checked them periodically (within the app) and they stayed the same (and not relevant to me). They do not seem to match those on the website at the bottom of the dashboard, so I guess the recommendations API is kind of abandoned.

Also finding new shows via the "New episodes" and "Popular" lists will likely lead to better results anyway ("community recommendations"). Maybe also integrating a display similar function for shows and movies is better than that.
