### ISSUE TITLE
Web search does not use standard browser

### ISSUE THREAD

**Issue by ouzowtf** [UweTrottmann/SeriesGuide#610]
When I open IMDb, TheTVDB or trakt links of a show they are opened in the browser (Bromite) I set as standard on my system.
The same when using the vodster.de or VOD-search add-on.
However, when I use the web search add-on, the links open in the Samsung browser (beta) I have additionally installed.
There are no standards set to open links with in the system settings for Samsung browser or SeriesGuide.

I use SeriesGuide version 47 beta 1 and OOS 5.0.8 on my OP3T.

**Comment by UweTrottmann** [comment]
Thanks!

The web search extension uses an `ACTION_WEB_SEARCH` intent. This is different from the links to TheTVDB, trakt, etc.

I tried clearing all defaults for the Google app (my default for web search), then I could choose Samsung Internet. If I then clear all defaults for Samsung Internet I'm asked again to choose.

So: try clearing all defaults for Samsung Internet in Settings > Apps on your device.

**Comment by ouzowtf** [comment]
The Google app is deactivated for me and since those two apps seem to be the only one available for the "web search" activity, Samsung Internet is chosen by default.

Stupid situation :unamused:

**Comment by UweTrottmann** [comment]
You should ask the developers of your favorite browser to support the `ACTION_WEB_SEARCH` intent. It's pretty easy to do.
