### ISSUE TITLE
Update on material design 2.0?

### ISSUE THREAD

**Issue by gargullia** [UweTrottmann/SeriesGuide#615]
will be update on material design 2.0

**Comment by UweTrottmann** [comment]
What exactly do you mean by Material Design 2.0?

**Comment by UweTrottmann** [comment]
No response, closing.

**Comment by gargullia** [comment]
@UweTrottmann Well, for example, use android.support.constraint.ConstraintLayout as in all new applications of google. Or see how they implemented it in new books.
![screenshot_20190110-232953-329x658](https://user-images.githubusercontent.com/19420334/52572107-1d7fe000-2e28-11e9-8714-90eb753db6ea.png)

https://www.androidpolice.com/2019/01/10/play-books-is-the-latest-google-app-to-switch-to-the-updated-material-theme/
You can read more here.
https://material.io/tools/gallery/
https://material.io/design/material-studies/about-our-material-studies.html#
https://uxdesign.cc/previewing-material-design-2-0-ec0215f0588f

**Comment by UweTrottmann** [comment]
Uhm, https://github.com/UweTrottmann/SeriesGuide/search?q=ConstraintLayout&unscoped_q=ConstraintLayout

SeriesGuide is using these components already. If you are asking that I copy the exact design of the Play Store or Google apps, then that's not going to happen.

Material Design 2.0 just makes them more flexible so different shapes or fonts are easily possible. Though I don't see a benefit for SeriesGuide here. You would have to come up with more concrete suggestions.
