### ISSUE TITLE
Generated ButterKnife code only included on rebuild in APK

### ISSUE THREAD

**Issue by UweTrottmann** [UweTrottmann/SeriesGuide#616]
Reverted to Android Gradle Plugin to 3.2.1 as the R file changes too often.

R file IDs seem to change on every little layout modification, requiring a rebuild to avoid butterknife view binding from crashing.

This is annoying when quickly iterating on a layout as fast, incremental builds are unusable. Let's hope the Gradle Plugin receives bug fixes in that regard as I could not find a quick solution from the butterknife side (the code generation likely only runs if sources change, not layouts).

**Comment by UweTrottmann** [comment]
OK, this is totally weird as it only seems to affect `ShowsDiscoverFragment`. Investigating.

**Comment by UweTrottmann** [comment]
Doesn't make any sense at all. Crashes with:
```
java.lang.IllegalStateException: Required view 'textViewHistoryEpisode' with ID 2131297058 for field 'title' was not found. If this view is optional add '@Nullable' (fields) or '@Optional' (methods) annotation.
    at butterknife.internal.Utils.findRequiredView(Utils.java:88)
    at butterknife.internal.Utils.findRequiredViewAsType(Utils.java:100)
    at com.battlelancer.seriesguide.ui.search.ShowsDiscoverAdapter$LinkViewHolder_ViewBinding.<init>(ShowsDiscoverAdapter$LinkViewHolder_ViewBinding.java:21)
```
But in `ShowsDiscoverAdapter$LinkViewHolder_ViewBinding`:
```
target.title = Utils.findRequiredViewAsType(source, R.id.textViewGridLink, "field 'title'", TextView.class);
```
and `\app\build\generated\not_namespaced_r_class_sources\pureDebug\processPureDebugResources\r\com\battlelancer\seriesguide\R.java`:
```
public static final int textViewGridLink=0x7f090321; // is 2131297057
public static final int textViewHistoryEpisode=0x7f090322; // is 2131297058
```
also matches the IDs in `resources.arsc` in the debug APK.

Rebuild fixes things without any apparent reason why.

**Comment by UweTrottmann** [comment]
Ah dang it. Looking at the APK in the `ShowsDiscoverAdapter$LinkViewHolder_ViewBinding` byte-code the ID is incorrectly `const v2, 0x7f090322`. Oh well...

**Comment by UweTrottmann** [comment]
Long-term goal: remove ButterKnife. Maybe have a look at the announced ViewBindings library, if it ever ships.

**Comment by JakeWharton** [comment]
Oh, it'll ship!!

**Comment by UweTrottmann** [comment]
Pitfalls migrating to view binding so far:
- `<include>` tags need an `android:id`. Make sure to remove `android:id` from root view of included layout. https://medium.com/androiddevelopers/use-view-binding-to-replace-findviewbyid-c83942471fc
- When `<include>` layout root has `<merge>` manually `MergeLayoutBinding.bind(containingLayoutBinding.getRoot()`. https://stackoverflow.com/a/60260556/1000543
- When `<include>` layout file name differs by configuration, e.g. screen size, use `LayoutWideScreenBinding.bind(containingBinding.includeLayoutWideScreen)`.

**Comment by JakeWharton** [comment]
2 is weird. I would consider just eliminating the `<merge>` since the performance saving has basically become obsolete in 2020 compared to 2010.

**Comment by UweTrottmann** [comment]
@JakeWharton Eliminating `<merge>` means adding a wrapping `ViewGroup`, no?

Also: after a build, sync with Gradle to resolve red `ThatLayoutBinding` imports.
