### ISSUE TITLE
[BETA] Opening movie details from search may crash app

### ISSUE THREAD

**Issue by Jakob-Ruf** [UweTrottmann/SeriesGuide#622]
App crashes when opening some movies from search. Might be related to no details being available on TMDB

Settings:
Content language: EN
Publishing date: Germany

Reproduce with movie Hot Fuzz 2

Seriesguide version: v47-beta4 (Database v46), X Pass installed, trakt connected
Android 6.0.1 MMB29M, MIUI Global 10.1.1.0

**Comment by thouseef** [comment]
This can be reproduced in v47-beta4 

With v46 this listing has no valid data. But the app doesn't crash and displays null/no data.

**Comment by UweTrottmann** [comment]
Thanks, confirmed! Will work again with the next update.
