### ISSUE TITLE
Merge library projects or extract to artifact to improve build time

### ISSUE THREAD

**Issue by UweTrottmann** [UweTrottmann/SeriesGuide#623]

**Comment by JakeWharton** [comment]
This will actually slow down incremental builds because now there's more code in a single module.  It also means that parallelism can't be leveraged.

**Comment by UweTrottmann** [comment]
Thanks! Idea was to improve clean builds at least a bit, because they are 1 min+ since a few months (probably due to adding Kotlin to the build process). Turns out the gain (clean or incremental) is insignificant (~1-2 seconds).

It's only about 10 files so keeping them inline anyhow as that saves the trouble of maintaining build files.
