### ISSUE TITLE
Fabric plugin broken with Android Gradle Plugin 3.3.0

### ISSUE THREAD

**Issue by UweTrottmann** [UweTrottmann/SeriesGuide#626]
The Fabric plugin fails to add the Crashlytics API key to AndroidManifest.

Wait for an update to the Fabric plugin before updating to AGP 3.3 again.

**Comment by gabrielittner** [comment]
@UweTrottmann just as a heads up, if you use app bundles this is still broken with the latest Fabric gradle plugin

**Comment by UweTrottmann** [comment]
@gabrielittner Thanks, I verified it works. Not using app bundles.
