### ISSUE TITLE
Remove Build.VERSION_CODES.LOLLIPOP checks

### ISSUE THREAD

**Issue by UweTrottmann** [UweTrottmann/SeriesGuide#632]
Strangely lint did not find those:
`Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP`

Look for them and adjust code accordingly.

**Comment by JakeWharton** [comment]
The ObsoleteApiCheck should detect these. If not, please file a bug on the Lint component on the Google issue tracker.

**Comment by UweTrottmann** [comment]
@JakeWharton With minSdk 21, it does detect `Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP`.

But not `>=`.

Is that possibly on purpose?

**Comment by JakeWharton** [comment]
Definitely not. Comment on https://issuetracker.google.com/issues/72582320 with
your AGP version.

**Comment by UweTrottmann** [comment]
👍 https://issuetracker.google.com/issues/72582320#comment5
