### ISSUE TITLE
Discover movies - Could not talk to TMDb

### ISSUE THREAD

**Issue by SenorSmartyPants** [UweTrottmann/SeriesGuide#636]
V46.2-k on Android 4.4

Movies Discover tab is empty. If you click on the "popular" "digital releases" or "Disc Releases" tabs you get the Could not talk to TMDb error.

Movie history displays, but no movie poster images.

Watchlist display fine.

I know this version gets no new features, but I'm hoping you still fix bugs like this for a while.

Thank you

**Comment by UweTrottmann** [comment]
OK, confirmed. Looks like themoviedb.org no longer supports older (potentially insecure) encryption.

Can you make sure you have the latest version of Google Play services installed?
https://play.google.com/store/apps/details?id=com.google.android.gms

**Comment by UweTrottmann** [comment]
Turns out TMDB has turned off support for TLS v1.0.

I released an update (46.3-k) which tells Google Play services to update the security provider when SeriesGuide launches. This should enable modern TLS. Based on my tests with an emulator connecting to TMDB then succeeds.

**Comment by UweTrottmann** [comment]
OK, wrong explanation. Tried turning off TLS 1.0 on the image cache server, but requests then fail.

Looks like TMDB still supports TLS 1.0 and even SSL 3.0. But guarded by `TLS_FALLBACK_SCSV` (if I understand this correctly).
https://tools.ietf.org/html/rfc7507

Google Play Services ProviderInstaller seems to only update OpenSSL on the device which then supports `TLS_FALLBACK_SCSV`.
https://developer.android.com/training/articles/security-gms-provider

**Comment by SenorSmartyPants** [comment]
That update fixed it on my tablet as well. Thanks so much for the quick fix.
