### ISSUE TITLE
TMDB errors in Android Studio/emulator assistance

### ISSUE THREAD

**Issue by SenorSmartyPants** [UweTrottmann/SeriesGuide#638]
I'm very much a noob to android dev but I wanted to check out SG kitkat branch. But I'm running into TMDB time outs when going to show discovery tab. Very much like the bug you just fixed.

So I'm wondering if I need to run an emulator image with the play store, so it can update the SSL? Or if maybe this is just timeouts because I have to run ARM emulator images because x86 acceleration isn't supported on my setup.

I'm building the pureDebug kitkat branch and sending it to the emulator and it runs. So I'm that far anyway.

**Comment by SenorSmartyPants** [comment]
I am running images with the Google APIs.

**Comment by SenorSmartyPants** [comment]
I just hooked up my phone(5.1) to android studio and ran the app from master-k that I compile. Doesn't connect to TMDB to add shows, or discover movies.

I see these errors in logcat.

```
04-02 21:11:37.606 18916-18977/com.battlelancer.seriesguide E/tmdb_error: get shows w new episodes: 401 Unauthorized
04-02 21:12:22.825 18916-19608/com.battlelancer.seriesguide E/tmdb_error: get now playing movies: 401 Unauthorized
```

**Comment by GeoZac** [comment]
@SenorSmartyPants Semms like a API token issue, Are you sure you read through building guide [here](https://github.com/UweTrottmann/SeriesGuide/blob/dev/CONTRIBUTING.md#building)

**Comment by SenorSmartyPants** [comment]
Yes, that's what it is. I read that doc but apparently missed that.

Sorry for the hubbub. Me==noob.
