### ISSUE TITLE
Issues backing up to Google Drive

### ISSUE THREAD

**Issue by thdoan** [UweTrottmann/SeriesGuide#640]
I just noticed the following issues in v47 (though these could have been introduced earlier since I haven't backed up in a year):

1. sg-lists-export.json saves as a zero-byte file in Google Drive (oddly enough, sg-shows-export.json saves just fine).

2. Files are duplicated on Google Drive, even when saved using the same filename.

Both of these issues were not there when I last backed up to Google Drive in 2018.

**Comment by UweTrottmann** [comment]
On Google Drive files can be different, even if they have the same name. When picking the file always make sure to tap on the existing file and then choose yes when asked to overwrite after tapping save.

If you don't have lists the backup file will remain empty. But I suspect this should clear itself up due the above.

**Comment by thdoan** [comment]
Thanks for the quick solution.
