### ISSUE TITLE
Recent list capped at 4 weeks in v49-beta1?

### ISSUE THREAD

**Issue by ferdnyc** [UweTrottmann/SeriesGuide#647]
The `v49-beta1` update brought some changes to the Recent list for TV Shows, with the episodes on the list now being grouped under headings like "**Thursday**" and "**Sunday 2 wk.ago**". That part's cool, _but_ the list now stops at 4 weeks of history.

Previously, my Recent list showed _**all**_ unwatched episodes, some going back many months or even years. As I recall that was a setting in the Preferences, and disabled by default, but it was something I'd turned on long ago. Now, though, the extended Recent list option seems to have turned itself off, and I can't seem to find the setting to re-enable it anymore.

Is it still possible to enable the old functionality for the Recent list?

**Comment by UweTrottmann** [comment]
See https://discuss.seriesgui.de/t/49-beta1-with-calendar-and-trakt-history-tweaks/192?u=uwe

**Comment by ferdnyc** [comment]
Fixed in v49-beta2 as noted in the release notes. Thanks!
