### ISSUE TITLE
Support for Trakt Resest Progress Feature

### ISSUE THREAD

**Issue by JoK3R-GER** [UweTrottmann/SeriesGuide#656]
Hello,

Thank you for your work. The app works great and I use it almost daily.

Recently Trakt added a new VIP feature which allows users to reset the watched progress of a show.
There is a possible solution given in the API docs (https://trakt.docs.apiary.io/#reference/shows/watched-progress) for realising it in clients.
Given your internal "watched" state, you might be able to set the state by using the additional information provided by the API.
I am willing to help with the implementation, but I have no experience with developing Android apps.

Kind regards

**Comment by UweTrottmann** [comment]
If this is truly only available for VIPs and being an advanced feature I guess you should use the trakt website.

Closing this as I use this issue tracker for bugs and tasks only.
