### ISSUE TITLE
TheTVDB Use thumbnail property instead of hard-coding path

### ISSUE THREAD

**Issue by UweTrottmann** [UweTrottmann/SeriesGuide#660]
Thumbnail URLs seem to change with the version 3 of TheTVDB API. Use the thumbnail path returned by the API instead of manually building it.

Edit: Also apparently the base URL will change to `https://artworks.thetvdb.com/banners`. Though there [will apparently be a 302 redirect](https://forums.thetvdb.com/viewtopic.php?f=118&t=58139&sid=03da86f09b085f0b6fe4283075271dd1#p157099) from the old base URL `https://www.thetvdb.com/banners` ("don't break URLs").

**Comment by olliebean** [comment]
I presume this is why all my series thumbnails seem to have vanished from the app? A couple disappeared recently, and I did a "Sync & Download all" in the hope they would reappear, instead of which all the other thumbnails vanished as well.

**Comment by UweTrottmann** [comment]
Unrelated issue (see https://discuss.seriesgui.de/t/thetvdb-issues-no-posters-can-not-add-shows/316). This is regarding future-proofing the app for an upcoming API change at TheTVDB.com.
