### ISSUE TITLE
Add show: unable to talk to trackt/thetvdb

### ISSUE THREAD

**Issue by daniele-athome** [UweTrottmann/SeriesGuide#666]
I'm unable to add new shows since a few days - after upgrading to v51-beta2. Even the show preview dialog can't load any information.

Logcat doesn't show anything - I mean no logging whatsoever, you should really log something :-)

**Comment by git-tili** [comment]
Same here. History doesn't update either. The "trakt" menu shows a red X next to TheTVDB.

**Comment by UweTrottmann** [comment]
See https://discuss.seriesgui.de/t/51-beta1-2-fixes-bugs-future-proofs-for-thetvdb-com-changes/372?u=uwe.
