### ISSUE TITLE
Add an option to notify about new episodes after the release instead of before

### ISSUE THREAD

**Issue by najodleglejszy** [UweTrottmann/SeriesGuide#684]
Right now, the "When to notify" option in app's settings only lets me set notifications about new episodes of my tracked shows minutes, hours and days _before_ the release. I would like to have an option to get a notification, say, a day after a new episode airs.

**Comment by UweTrottmann** [comment]
Try to set a time offset in advanced settings instead.

**Comment by najodleglejszy** [comment]
I didn't notice that setting. Thanks a ton for the suggestion, it's just what I needed!
