### ISSUE TITLE
Unable to add new shows

### ISSUE THREAD

**Issue by oliverschloebe** [UweTrottmann/SeriesGuide#690]
Hi @UweTrottmann,

I am unable to add new shows as it sais "Could not add `<show>`. The show does not (yet) exist on TheTVDB." but it does exist.

![Error message](https://i.imgur.com/xzhECEL.jpg)

Is this an app or TheTVDB API issue?

Thank you!

**Comment by yonifra** [comment]
Was about to add this bug as well. The Mandalorian is already in TheTVDB database https://www.themoviedb.org/tv/82856-the-mandalorian

**Comment by Dashue** [comment]
Same here

**Comment by Craicerjack** [comment]
Having same issue with watchmen and his dark materials

**Comment by oliverschloebe** [comment]
Seems to be working again. :+1:

**Comment by Dashue** [comment]
Mine is not working

**Comment by Dashue** [comment]
I realized I can't add a show if I search for it using English language filter. Putting it to any language and doing a search allows me to add it

**Comment by Craicerjack** [comment]
Given what Dashue said

I was able to add his dark materials via the discover section. 
It was available as `(en)`  
When I searched for it, it didnt give me language options and the only result was shown as `(all)`

**Comment by UweTrottmann** [comment]
See https://discuss.seriesgui.de/t/thetvdb-issues-with-missing-episodes-images-adding-shows/527 for more details on the TheTVDB issues.

As for search the next update will use TheTVDB again for English language search (as for all other languages) as their engine has improved drastically.
