### ISSUE TITLE
(Request) Remove Crashlytics

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [UweTrottmann/SeriesGuide#699]
Please remove Google Crashlytics
![](https://i.imgur.com/oC6hNdV.png)

**Comment by UweTrottmann** [comment]
Thanks for your request. First of all: I do not use the tracking features of Crashlytics (namely Answers). It is only used for crash reporting. See https://seriesgui.de/privacy for what data is collected.

Anyhow, there is currently no viable alternative that I am aware of. The Android Vitals crash reports in the Play Console are too unspecific (e.g. no exception messages).
