### ISSUE TITLE
App data wasn't restored upon switching to another device

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [UweTrottmann/SeriesGuide#700]
I've switched from Pixel 2 to Pixel 4, and all of the app's data was reset, including the entire watch list.

Please fix this. Make the app auto-backup using Google's cloud. 

I don't get why it was all lost. Looking at the source code, I can see that the manifest does have the backup flag turned on.

How could it be?

**Comment by UweTrottmann** [comment]
Android's full app backup feature is hit and miss. I'm seeing this for other apps as well. Not sure what I can improve here.

If you still have your old phone and did turn on auto-backup you might be able to transfer the exported JSON files and restore them on your new device. https://seriesgui.de/help#backup

**Comment by UweTrottmann** [comment]
Yeap, just checked the docs and [there is a size limit of 25 MB](https://developer.android.com/guide/topics/data/backup#Choosing). So: use the backup tool inside the app. Or if that is too much hassle, please subscribe and use SeriesGuide Cloud.

**Comment by AndroidDeveloperLB** [comment]
Well, you can backup only what's important. It can't be that the DB for what the user has done would be too large. The most important stuff is the series that the user has chosen and those that were marked as watched. Also settings could be good.
The size limit is 25MB. It's enough for this kind of data.
And even if it's not, you can always offer a Google Drive sign in. 
I lost everything I've chosen. I couldn't copy from the previous device because I've factory reset it.

Please fix this. It's unfair that many apps do offer this (example : "Hobi"), and this one can't.
