### ISSUE TITLE
Remove Analytics 

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [UweTrottmann/SeriesGuide#701]
Would appreciate it greatly if you removed Google Analytics from the f-droid release.

**Comment by UweTrottmann** [comment]
Sorry, but there is no official release on f-droid. Also SeriesGuide has 
not used Google Analytics for a year now.

I suggest downloading via Google Play, Amazon or get the APK here from GitHub.

Am 28. Dezember 2019 21:56:35 schrieb Gravity <notifications@github.com>:

**Comment by Z3ROGRAV1TYx** [comment]
@UweTrottmann https://f-droid.org/packages/com.battlelancer.seriesguide/
It could very well be grabbing from one of my added repos. Probably IzzyOnDroid.

Either way whatever it is, it says updated 3 weeks ago, and Exodus Privacy is generating a report for it showing Google Crashlytics as late of December 17th.

**Comment by UweTrottmann** [comment]
That link returns a 404 Not Found for me. Anyhow, as I said, I do not release the app on F-Droid. The app would not be accepted anyhow because it uses Google Crashlytics, as you said.

I do not use Crashlytics to track you, see https://seriesgui.de/privacy.
