### ISSUE TITLE
Request: make the series-details screen to taken whole screen instead of a dialog

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [UweTrottmann/SeriesGuide#702]
This is a huge dialog:

![image](https://user-images.githubusercontent.com/5357526/71723058-e34e7100-2e33-11ea-8751-ccc9b8a67010.png)

I think it's better to just show it in full display like normal screens.

You could add more options to it too, such as :
Search on Google, click on thumbnail for viewing it in full screen. Share name (to send to somewhere else), text selection of part of the description...

**Comment by UweTrottmann** [comment]
Thanks for the suggestion.

**Comment by AndroidDeveloperLB** [comment]
Why close it then?
A lot of times it gets a scrollable content, and if it was in a normal full display it wouldn't.
Plus it lacks a lot of possible interactions and doesn't let me even select the text well...
