### ISSUE TITLE
Duplicate watch history

### ISSUE THREAD

**Issue by mschumacher69** [UweTrottmann/SeriesGuide#709]
I've been using SeriesGuide to mark episodes as watched manually, but I recently started using [Nova](https://github.com/nova-video-player/aos-AVP) to scrobble.

I've been having some duplicates in my watch history since I started scrobbling and I've been trying to figure out what's causing it.

I have noticed that the watched icon is different between the original watch and the duplicate in SeriesGuide (check attached screenshot). I think the check mark means it's been set as watched manually and the chat bubble means it's been scrobbled automatically. But I haven't been marking episodes manually since I started scrobbling with Nova.

I'm suspecting that SeriesGuide is duplicating the watch once it syncs with trakt. Is there a way to check the log to check the source of the watches to figure out if the duplicates are from SeriesGuide or from Nova?

Thanks
![73598625-c056d000-454b-11ea-9606-2551d0ab545c](https://user-images.githubusercontent.com/461871/73607021-02225d80-45c2-11ea-94e0-b43f13691bd1.png)

**Comment by UweTrottmann** [comment]
Except for the first time syncing, SeriesGuide does not upload watched episodes. It considers Trakt as the source of truth. Either this is an issue with Nova or worst case the Trakt history API.
https://github.com/UweTrottmann/SeriesGuide/blob/92b9c7fda7925095e26054e632eb1f9cd76c50c5/app/src/main/java/com/battlelancer/seriesguide/sync/TraktEpisodeSync.java#L64-L69

And your observation is correct, the check mark means marked watched and the chat bubble check-in or scrobble.
https://github.com/UweTrottmann/SeriesGuide/blob/92b9c7fda7925095e26054e632eb1f9cd76c50c5/app/src/main/java/com/battlelancer/seriesguide/ui/streams/SectionedHistoryAdapter.java#L108-L115

**Comment by mschumacher69** [comment]
Thanks.
