### ISSUE TITLE
Multiple trakt accounts

### ISSUE THREAD

**Issue by Vampire** [UweTrottmann/SeriesGuide#729]
I'd like to suggest the feature to be able to add multiple trakt accounts.
Usually if I watch series or movies, I'll do so together with my wife.
It would be great if I could set an episode or movie to watched state in trakt for both of us and optimally also have features like searching for things I watched alone, searching for things we watched together and searching for things she watched without me.
Of course it should still be possible to set things as watched only for myself.
The account(s) added additionally should be somewhat secondary, so that for example posting comments is done with the primary account, but giving ratings, setting as watched or checking in can be done for one of the accounts or multiple.

**Comment by UweTrottmann** [comment]
Thanks for the suggestion. For now this is way out of scope as there are many other things to do.
