### ISSUE TITLE
The app does not respect the system font size.

### ISSUE THREAD

**Issue by akdevservices** [UweTrottmann/SeriesGuide#730]
The app does not react to changing the system font size. The application UI fonts are too small and there is no way to change them.

It seems that the bug was intoduced in the last year, earlier the app worked as expected.

Android 5.0.2
Display: 540x960 pixels, 220 ppi

**Comment by UweTrottmann** [comment]
Thanks for reporting. This is an issue with the Google appcompat library the app is using.
https://issuetracker.google.com/issues/140607881

This will be fixed with the upcoming appcompat 1.2.0 release (confirmed fixed as of 1.2.0-alpha02).

**Comment by UweTrottmann** [comment]
Will ship the release candidate of appcompat with `55-beta3`, should be stable enough and doesn't pull in any other preview versions of dependencies.
