### ISSUE TITLE
Bugs with language and images

### ISSUE THREAD

**Issue by fabianski7** [UweTrottmann/SeriesGuide#731]
Hi, your app is a salvation for those who don't use google play services. Thanks for your support.

But I'm experiencing some bugs with the images and titles of the movies and series. My language is not English so I switched to Portuguese in the three places I found this option: in the list of [series](https://mega.nz/#!gZdnlCrY!n2ThCdO2m7f5iIIJQDj2hR9qB1bAiXLfJhQqgaW1Frk), [movies](https://mega.nz/#!hQURwCjD!8-Dhs7WQkRa3v3lnNwy9elccU2MlroeN6U9yEQFk1ig) and [application settings](https://mega.nz/#!AcFThSIK!eduz2SYSqaDyEapUHRaeHxEMb85qqOcfLudvC-eMeW8). Before that, I had cleaned the app data to make a more accurate test and then I logged in with my trakt account.

These are the bugs I found

**1. Series images are not uploaded**

Video [V1](https://mega.nz/#!0AdTAK4a!j1NsVHajLgCF20JdPIWGrq5---_C2QVSfjbd0VPDs-M) [V2](https://mega.nz/#!RQNBGaaR!ZtEolJzathFxLElJLIhv9bhGdAPf4DTMebyW44slsjk)
Screenshots [S1](https://upload.vaa.red/65FsJ#9e709ef1a6372565bf3ba1ea3bdd0d8d) [S2](https://upload.vaa.red/2scewZ#a330a1a15df5f344665e877a9db7a0b7) [S3](https://upload.vaa.red/jBydJ#34a0aede35fc81eac6807d7662c71ff4) [S4](https://upload.vaa.red/YCHD5#6d5013654198de89ba0ac7595fb91ab0) [S5](https://upload.vaa.red/23QxjQ#5270bf3866ef18b5d2f1d4c2363ea652) [S6](https://upload.vaa.red/gXD2f#c60cf566d4aaeb566b00839936c6bcca)

In this video [V1], I tried to show with the bug that occurs. When the series is in Portuguese, the image is not loaded, but by changing the language back to English, it is displayed correctly [S1] [S2] [S3].

The same bug occurs in the "recent" series option [S4], and "coming soon" [S5]. No image is displayed.

This problem with the images only happens with the series. With the films, the images are loaded without problems in the languages tested 

The history of watched episodes in the series [S6] does not have that problem either.

The only series that didn't happen was "Dragon Ball." The image is uploaded in both languages. I also showed it in the second video [V2].

**2. The names of the films on some screens are translated and on others not**

Screenshots [S1](https://upload.vaa.red/SK4xs#2c21e59ec554ebacc0ec4a814d103c1e) [S2](https://upload.vaa.red/Z9kLE#b04fd2c74979944ecc0ff647a8177c9e)

In [S1], in the history option, the name of the film is in English: "A Dog's Will". But in the [S2], in the list of films watched option, the name is correctly displayed in Portuguese: "O auto da compadecida". Since I chose the Portuguese language in all available settings, the correct one would be to show the Portuguese version in all options (history, watched list, etc.)

I hope I was able to explain that problem clearly. It's a little confusing because the bug happens in different ways in different options. 
If you need more details, I can send it to you.

**Comment by fabianski7** [comment]
Maybe it's something related to that, too
https://discuss.seriesgui.de/t/language-sinopse-movies-series/646

**Comment by UweTrottmann** [comment]
Make sure to set the alternative language for shows to English in Settings > More. Most series don't have a Portuguese poster.

If SeriesGuide is connected to Trakt it will show it's history page. Trakt currently is English only, hence the history items are in English.

**Comment by Blackspirits** [comment]
Boas fabianski7, vou falar português, pois mandas-te-me um email e pelo que percebi és brasileiro.

Ou seja, nas séries apenas existe um "português", pois o SeriesGuide vai buscar os dados ao TVDb, que até a uns meses eles não faziam diferença entre pt-pt e pt-br. Agora já fazem essa diferença mas o SeriesGuide ainda não atualizou isso, e no link que adicionaste acima é o que eu estou a pedir ao Uwe para fazer.

Nos filmes o SeriesGuide vai buscar ao TMDb e não ao TVDb. O TMDb já faz distinção de pt-pt e pt-br a vários anos. Por isso, nos filmes podes escolher "português (Brasil)".

Outra coisa que tens que saber se ainda não fizeste atenção, o idioma dentro das séries e dos filmes apenas é para mudar a Sinopse/Descrição, nada mais.

E quanto as imagens aparecer em pt-pt , pt-br ou noutro idioma sem ser o inglês, neste momento não é possível o SeriesGuide vai buscar as imagens ao Trakt. E o Trakt apenas tem as imagens originais (normalmente em inglês). Apenas e só quando o Uwe decidir ir buscar as imagens ao TMDb ou ao TVDb (eu prefiro o TMDb pois já tem muito mais imagens em vários idiomas)  pelo idioma que cada utilizador/usuário tem predefinido no telemóvel é que poderá aparecer, até la não.

Para te aparecer sempre as imagens e não ficar em preto, tens que ter nas definições/configurações -> em avançado -> Idioma alternativo -> Inglês (Como diz o Uwe em cima)

Se tiveres as imagens a atualizar por Wi-fi tens que ter a certeza que estas numa zona com Wi-fi para atualizar automaticamente.

Quanto aos títulos, se aparecer noutro idioma é porque no TMDb ou no TVDb ainda não esta atualizado. E nas séries pode acontecer de te aparecer algumas em pt-pt e outras em pt-br pois como disse acima o SeriesGuide ainda não atualizou isso.

Qualquer duvida não hesites...

**Comment by fabianski7** [comment]
@UweTrottmann 
Yes, I realized that the posters of the movies are not available in Portuguese in the trakt, but wouldn't it be possible to force the use of the posters in English when the selected language is Portuguese? 

The history of the trakt is actually shown in English, but if I add a new movie inside the seriesguides it will be shown in Portuguese. And even if I clear all the app data and connect my account again, that same added movie will be shown in Portuguese. That is, even if I load it from the trakt history, it will be shown in Portuguese. So I think it's something that has a solution.

**Comment by fabianski7** [comment]
English
The titles of all the films I've tested are available on TMDB, the series as well. I don't think the app is handling this in the right way. Unfortunately, people usually ignore any language other than English. 
I don't think we will have the seriesguide working as it should in our language, since it has already closed this issue.

Portuguese
Os títulos de todos os filmes que eu testei estão disponíveis no TMDB, ás séries também. Acho que o aplicativo não está lidando com isso da forma correta. Infelizmente, as pessoas costumam ignorar qualquer outro idioma além do inglês. 
Acho que não teremos o seriesguide funcionando como deveria na nossa língua, já que ela já fechou esse issue.
