### ISSUE TITLE
Change the color of the spinning wait cursor

### ISSUE THREAD

**Issue by akdevservices** [UweTrottmann/SeriesGuide#732]
Please, consider changing the color of the spinning wait cursor in the light theme. It could be white, light grey, yellow or any color you like that has higher color contrast. Current color contrast of the spinning wait cursor to the background is 1.35:1. That's pretty low.

You can experiment with color contrast using this calculator.
https://webaim.org/resources/contrastchecker/

![image](https://user-images.githubusercontent.com/29972256/78340448-ce05f180-759e-11ea-8ca0-4a491aac40da.png)

**Comment by UweTrottmann** [comment]
Thanks. I'm aware of the tool and have used it a lot when building the new themes. I ignored the values for the progress indicator as it does not really have to be read, just seen. I'll have another look.
