### ISSUE TITLE
TMDB issue

### ISSUE THREAD

**Issue by bast69** [UweTrottmann/SeriesGuide#747]
[2020-06-18 2313 PM.log](https://github.com/UweTrottmann/SeriesGuide/files/4801223/2020-06-18.2313.PM.log)
Hello,
I have a issue during the sync with this message : failed to update movie ("cyborg", TMDB id 298622).

But I didn't see this movie and in the website this id doesn't exist.

**Comment by UweTrottmann** [comment]
Look under Movies in your watchlist, collection and watched tab for this movie. Then remove it.

**Comment by bast69** [comment]
Great, I found the movie in my watchlist. I close this issue.
