### ISSUE TITLE
Show status not displayed on phones in portrait

### ISSUE THREAD

**Issue by daniele-athome** [UweTrottmann/SeriesGuide#749]
I can't see the show status (Ended, Continuing, etc.) since the latest update. If I put my phone to landscape it appears again. I believe this was even intended maybe, but I'm opening a bug just in case :-)
https://github.com/UweTrottmann/SeriesGuide/commit/5066612399f861f1f7faa1165babec90c6c1cc18#diff-e1b528d167549074b691b3c23ef1db07L58

But may I ask why? I can't find other ways to see it in portrait.

Portrait:
![Screenshot_20200718-102124](https://user-images.githubusercontent.com/3763726/87848402-7b97d900-c8e0-11ea-9523-55b7acaa5f8a.png)

Landscape:
![Screenshot_20200718-102208](https://user-images.githubusercontent.com/3763726/87848416-94a08a00-c8e0-11ea-85a7-7dd4ed8cafbd.png)

**Comment by UweTrottmann** [comment]
On purpose to make room for the buttons. Status has moved to the top of the overview tab. Thanks for your feedback!

**Comment by daniele-athome** [comment]
Damn I didn't really see that! :D Thank you.
