### ISSUE TITLE
[BUG] show history does not display

### ISSUE THREAD

**Issue by Cologler** [UweTrottmann/SeriesGuide#758]
- app version: 56
- db version: 48

show watch history only displays on the history page, not on the history tab:

![Screenshot_20201024-122840_SeriesGuide](https://user-images.githubusercontent.com/10906962/97067885-19442800-15f5-11eb-895e-07e106a6d99d.jpg)

![Screenshot_20201024-122856_SeriesGuide](https://user-images.githubusercontent.com/10906962/97067887-1c3f1880-15f5-11eb-86e1-9d4fe4a319e9.jpg)

**Comment by Cologler** [comment]
Today it worked again.

**Comment by UweTrottmann** [comment]
Note: This page is powered by Trakt. Their servers have been stressed until they implemented fixes and rate limiting a few days ago.

https://twitter.com/trakt/status/1321166733651054594
