### ISSUE TITLE
Bug: can't choose "-" for when to notify me about new episodes, to show the notification AFTER the episode is available

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [UweTrottmann/SeriesGuide#760]
**Describe the bug**
I wanted to show the notification after the episode is available, and not before (because I can't watch it before it's available), but it doesn't let me.

**To Reproduce**
1. settings->notifications->when to notify
2. Choose days.
3. Since it says "before", write "-1" to mean "a day after it's out".
4. Notice it doesn't let you.

**Expected behavior**
To let me have the notification after a day.

**Screenshots**
Here:

[device-2020-11-06-103736.zip](https://github.com/UweTrottmann/SeriesGuide/files/5500092/device-2020-11-06-103736.zip)

**Smartphone (please complete the following information):**
Pixel 4
Android 11
Various, but not related anyway
Various, but not related anyway

**Additional context**
:(

**Comment by UweTrottmann** [comment]
Use the manual time offset feature in advanced settings to move the release time back (or forwards).

**Comment by AndroidDeveloperLB** [comment]
@UweTrottmann Why is it in advanced? Why can't I have it in the normal settings?
Why have duplicate settings to do the same thing?
