### ISSUE TITLE
Can't sync watched status of Series from Trakt

### ISSUE THREAD

**Issue by auanasgheps** [UweTrottmann/SeriesGuide#761]
**Describe the bug**
I've been using since a lot SeriesGuide with Trakt and I today I've discovered an issue.

There's a TV Show from Netflix (_How To Sell Drugs Online_) that SeriesGuide doesn't... like. 
After watching this show, I imported the watch status in Trakt via a Chrome extension and is showing correctly in Trakt. However, SeriesGuide is unable to pick it up.
The funny thing is that SeriesGuide acknowledges I have watched this show in the _History_ tab, but when I open this show's tab, it says I still have to watch the second season.

I'm Italian, but never had an issue with matching series/episodes from Trakt, which are shown in English. Again, been using this integration for more than two years and has always worked perfectly for both movies and series. Am I missing something?

**To Reproduce**
Well, don't really know if this can be reproduced.
1. Watch this show on Netflix
2. Import it in Trakt using traktflix
3. Confirm has been improted successfully in Trakt
4. Open SeriesGuide, observe is being shown in history but not marked as watched 

**Expected behavior**
As usual, SeriesGuide should mark episodes/seasons as I import them in Trakt.

**Screenshots**
Season 2 is still not watched
<img src="https://user-images.githubusercontent.com/20586878/98745202-6248fa00-23b3-11eb-9a68-de925ca97cdc.jpg" width=40% height=40%>
But I did it, I swear!
<img src="https://user-images.githubusercontent.com/20586878/98745198-6117cd00-23b3-11eb-82d5-2bcf72243a7f.jpg" width=40% height=40%>
**Smartphone (please complete the following information):**
 - Device: Galaxy S9+
 - OS: Android 10
 - Browser: what?
 - Version SeriesGuide v56

**Additional context**
Always worked great, never had an issue with this functionality.

**Comment by UweTrottmann** [comment]
Thanks for the detailed report! Just some basic things to get out of the way:
- Did you try to disconnect and connect Trakt again?
- Can you check the sync settings of your device: https://seriesgui.de/help#syncfail
- What happens if you set an episode from season 2 watched from SeriesGuide?

**Comment by auanasgheps** [comment]
> Did you try to disconnect and connect Trakt again?ù

lol, so simple I didn't tried this. As soon as I logged in again, it synced correctly what was pending. 

Thanks for the API explanation, I had the feeling they were two different streams.

**Comment by koichirose** [comment]
I'm having the same issue. Tried disconnecting trakt and reconnecting. I can see episodes in my history and I can see check-ins on trakt, but the watch status is not updated in the app, it's stuck at a few days ago.

**Comment by koichirose** [comment]
It fixed itself after about a week. I don't know what triggered the update.
