### ISSUE TITLE
[Images] Enable cross-signing for Lets Encrypt to keep supporting older Androids for longer

### ISSUE THREAD

**Issue by UweTrottmann** [UweTrottmann/SeriesGuide#764]
https://letsencrypt.org/2020/11/06/own-two-feet.html

Android 7.0 and below affected.

Or maybe Play Services Security Provider will get some kind of update?

Or maybe see https://github.com/square/okhttp/issues/6403

> As of **January 11, 2021**, we’re planning to make a change to our API so that ACME clients will, by default, serve a certificate chain that leads to ISRG Root X1. However, it will also be possible to serve an alternate certificate chain for the same certificate that leads to DST Root X3 and offers broader compatibility. This is implemented via the ACME “alternate” link relation. This is supported by Certbot from version 1.6.0 onwards.

https://community.letsencrypt.org/t/certbot-users-preparing-for-the-isrg-root-transition-january-11-2021/138059

> **Until July 1 2021**, Let's Encrypt will also continue to offer the Identrust certificate chain, for those who want to keep using it.

**Comment by yschimke** [comment]
To my understanding, Play Services Security Provider doesn't ship update CA certs.  You can confirm via a question on the LE forum.

**Comment by UweTrottmann** [comment]
@yschimke But maybe it will in the future. Hence the "*will* get some kind of update?".

What do you mean by "confirm via a question on the LE forum"?

**Comment by yschimke** [comment]
By LE forum I meant Let's Encrypt support forums. 

For play provider I guess ask on Google/Conscrypt project.  I can't answer for them.

**Comment by UweTrottmann** [comment]
Updated certbot (using snap now) and set
`preferred-chain = DST Root CA X3`
in `/etc/letsencrypt/cli.ini`.
https://community.letsencrypt.org/t/certbot-users-preparing-for-the-isrg-root-transition-january-11-2021/138059

This adds time until July 1, 2021 to come up with a solution for Android 7.0 and lower.

**Comment by UweTrottmann** [comment]
No longer relevant, Lets Encrypt found a solution (aka talk to the community).
https://letsencrypt.org/2020/12/21/extending-android-compatibility.html

Apparently it's fine to keep the `preferred-chain` argument (simply won't do anything).
