### ISSUE TITLE
Cannot sync Series from Trakt

### ISSUE THREAD

**Issue by auanasgheps** [UweTrottmann/SeriesGuide#770]
**Describe the bug**
I installed SeriesGuide on my new smartphone and signed in with Trakt.
To my surprise, only Movies are being synced. 

**To Reproduce**
1. Go to More > Trakt
2. Login
3. Movies sync, Series don't

Statistics do also confirm it.
Obviously I do have loads of series in Trakt!

**Expected behavior**
I expect to sync Series as usual.

**Screenshots**
![Screenshot_20201205-172835](https://user-images.githubusercontent.com/20586878/101255727-67356b00-371f-11eb-94c2-38392544323b.jpg)
![Screenshot_20201205-172830](https://user-images.githubusercontent.com/20586878/101255733-67ce0180-371f-11eb-89ac-58d1202bb3c3.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 8T
 - OS: Android 11
 - Browser: N/A
 - Version 56

**Additional context**
I have put the app in debug mode, forced a sync and extracted the logs. I cam't see any clear error there.
[2020-12-05 1727 PM.log](https://github.com/UweTrottmann/SeriesGuide/files/5647408/2020-12-05.1727.PM.log)

I noticed that If I go to Shows > 3 menu dots > Sync Manually > Sync & Download All, the spinning wheel only appears for a fraction of a second, the sync can't actually be that fast.

Shows > History is correctly populated but you already told me in the past that this info is taken from a different API.

**Comment by UweTrottmann** [comment]
https://seriesgui.de/help#sync
> Unlike with Cloud, shows are not added automatically and the Lists section is not synced. But you can quickly access your Trakt show watchlist and watched and collected shows. https://seriesgui.de/help#library

**Comment by auanasgheps** [comment]
Allright, thanks for clarifying. I've been relying on Google Backup for a long time, which restored the app in its state, but I though this was coming from the sync.
