### ISSUE TITLE
UI Bug - Search box has different background color than app

### ISSUE THREAD

**Issue by yonifra** [UweTrottmann/SeriesGuide#774]
**Describe the bug**
The searchbox background color is different than the background color of the app itself.

**To Reproduce**
1. Go to the "Discover" tab
2. Click on the search box
3. Notice that the box's background is slightly lighter than the app's

**Expected behavior**
The search box should have the same background color as the app

**Screenshots**
![image](https://user-images.githubusercontent.com/726718/103415355-6c54d100-4b8a-11eb-9eb6-f595309fd9bd.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] Galaxy S10+
 - OS: [e.g. iOS8.1] Android 10
 - Version [e.g. 22] 57

**Additional context**

**Comment by UweTrottmann** [comment]
This is by design, sorry :)
