### ISSUE TITLE
Autobackup path

### ISSUE THREAD

**Issue by Offerel** [UweTrottmann/SeriesGuide#775]
The application tells me that a autobackup was successfully created. But where are this files saved?

![Screenshot_20210102-170036_SeriesGuide.jpg](https://user-images.githubusercontent.com/14041522/103461125-3ba4a100-4d1c-11eb-8955-5ada6601796d.jpg)

The path /storage/emulated/0/Android/data is empty...

**Comment by UweTrottmann** [comment]
They are in the application specific directory on internal storage. E.g. something like /Android/data/com.battlelancer.seriesguide/files/Backups.

If you need these files I suggest to enable the create copies option and choose a location.
