### ISSUE TITLE
APK download

### ISSUE THREAD

**Issue by ReIaxo** [UweTrottmann/SeriesGuide#778]
Hi, normally I download the APK of SeriesGuide from the release page, but it is not attached for version 57. And from your Website (alternative download), you also link to the release page.
Went something wrong in your pipeline?

And another question: Can I get the supporters benefits without having a Google account? Would like to use the rewatch feature.

Thank you for building such a great app and in advance for helping me.

**Comment by UweTrottmann** [comment]
Thanks! I simply forgot to upload it: https://github.com/UweTrottmann/SeriesGuide/releases/tag/v57

I recommend to install via Play Store or Amazon App Store to ensure you always get the latest version. This is also the only way to get the subscription only features.

**Comment by ReIaxo** [comment]
Thank you for uploading.

I know, but I try to dodge Google and others the most I can because I want to keep my privacy.

If there is any way to get the subscription only features nevertheless, maybe with he Beta program or sometimes in the future please let me know.

**Comment by ReIaxo** [comment]
Hi, I have to bring this up again. Looks like you forgot to upload it again for version 70.0.2 and 70.0.3? Is it a manual process which can not be automated?

**Comment by UweTrottmann** [comment]
Sorry, I will probably not longer upload the APK to GitHub. Someone else recently cloned SeriesGuide (and just changed the name, keeping all credentials, API keys, etc.) and submitted it to the Play Store and I'm failing to get it removed. So I do not longer want to make it easy to get the latest APK.

So for now the only official options are to download via Google Play or Amazon Appstore.

**Comment by grrrrr** [comment]
It is a bit unfortunate to hear this albeit late.   I know you have made your mind up but on the small chance there is any hope of you re-releasing apk on github it would be very much appreciated.

Removing it from here doesn't make it much harder if at all to clone the apk (available via many apk sites or with tools like gplaydl) but does increase the steps for those of us who are eschewing the google ecosystem to easily install the trusted apk (e.g. with obtanium).

**Comment by UweTrottmann** [comment]
Added the universal APK back.

**Comment by grrrrr** [comment]
@UweTrottmann thank you very much for this.   We appreciate it and the great app :D
