### ISSUE TITLE
imdb link on episode links to show on imdb

### ISSUE THREAD

**Issue by flabbamann** [UweTrottmann/SeriesGuide#792]
**Describe the bug**
If I click on the imdb link on an episode the link leads to the show on imdb, even if the episode has the imdb id added on tmdb. This only happens on shows added from tmdb. On shows migrated from tvdb the links are correct.

**To Reproduce**
1. Add a show from tmdb that has imdb links for the episodes (e.g. Mr Robot)
2. Click on the IMDB link on an _episode_
3. The link leads to the _show_ on imdb

**Expected behavior**
The imdb link on an episode should link to the corresponding episode entry on imdb, if the id is added on tmdb.

**Smartphone (please complete the following information):**
 - Device: Oneplus 5T
 - OS: Android 11
 - Version 58.2

**Comment by UweTrottmann** [comment]
Sorry, this works as expected. TMDb does not have IMDB IDs on the episode level.

I guess it makes sense to remove the button from the episode screens?

**Comment by flabbamann** [comment]
It does :)
![grafik](https://user-images.githubusercontent.com/7760172/117160549-7c432280-adc1-11eb-9a6f-d816113a073d.png)
https://www.themoviedb.org/tv/456-the-simpsons/season/32/episode/1/edit?active_nav_item=external_ids

https://developers.themoviedb.org/3/tv-episodes/get-tv-episode-external-ids

**Comment by UweTrottmann** [comment]
Oh, thanks. I guess I decided against querying external IDs for each episode then to avoid overloading the TMDb API.

Keeping this open to add support for e.g. on demand fetching of external IDs. Though I'll be honest and say this isn't a priority as the data source is TMDb.

**Comment by UweTrottmann** [comment]
With the next update SeriesGuide will load the episode ID on demand from TMDb. If it's not available it will still use the show ID (if that is available).
