### ISSUE TITLE
inlcude adult content in the search results.

### ISSUE THREAD

**Issue by odnar-dev** [UweTrottmann/SeriesGuide#793]
**Describe the bug**
I was looking to add [Deep Space 69](https://www.themoviedb.org/search?query=Deep+Space+69),
this serie is listed at tmdb, but is not available (with search) on SeriesGuide.

**To Reproduce**
1. Go to 'Discover'
2. Type 'Deep Space 69'

**Expected behavior**
same as the website

**Additional context**
i know that enabling this may include some pornography material in search results, but can you at least let the user choose (in the settings , disabled by default)

**Comment by odnar-dev** [comment]
look like you already working on it 👍🏻 

https://github.com/UweTrottmann/tmdb-java/pull/84

**Comment by UweTrottmann** [comment]
Sorry, this option will likely never be available due to Google Play Store (and other app store) policies.
