### ISSUE TITLE
Distinguish variant of chinese languages data source from TVDB/TMDB.

### ISSUE THREAD

**Issue by hebeguess** [UweTrottmann/SeriesGuide#794]
**Describe the bug**
SeriesGuide, the app UI itself supported Traditional Chinese and Simplified Chinese for many years.
However, when it comes to pulling show data it doesn't distinguish between them and default to Simplified Chinese.
The app only able to pull a show data if it had Simplified Chinese entries.

The data source SeriesGuide uses TVDB/TMDB both supported three variants: Traditional Chinese (zh-TW), Simplified Chinese (zh-CN), and Traditional Chinese/Cantonese (zh-HK).

Currently 'preferred content language' under each show/movie page and 'alternate language' under Settings only offers single option as 'Chinese' which default to pulling Simplified Chinese (zh-CN) from TVDB/TMDB.

**To Reproduce**
On SeriesGuide 58.2, pulling Tawainese show data from TMDB came up with mostly empty entries ('translation not available') as it only has Traditional Chinese episodes data entries.

**Expected behavior**
The app should be able to distinguish among these 3 major variants of Chinese languages and pulling show data accordingly.
The 'preferred content language' and 'alternate language' functions should offer additional choices as well.

**Comment by UweTrottmann** [comment]
Thanks for reporting!

Current state: for shows only `zh` is available, for movies `zh-CN` and `zh-TW`.

State at TMDb:
![image](https://user-images.githubusercontent.com/888674/117984355-12ce9100-b338-11eb-8164-618cb7df3f71.png)

Add `zh-HK` to movies, add variants for shows (similar to `pt` and `pt-BR`?).

**Comment by UweTrottmann** [comment]
This should be resolved with SeriesGuide 59. Let me know if there are still issues then!

**Comment by hebeguess** [comment]
Thanks. I am not on the Android beta program, so I will wait for stable release.

Found additional small kinks on 58.5, on Movies side and using english UI.

The 'preferred content language' selection list show duplicated 'Chinese' entry.
Infact, one of them is 'Traditional Chinese' while another 'Simplified Chinese'

There is another entry on the list 'cn' which I assumed it meant to correspond to zh-cn,
but we already had one for the Simplified Chinese.
Selecting 'cn' also seems to caused movies fallback to english for me, guess it might be a null entry?
