### ISSUE TITLE
Request: offer "after" options for "when to notify" too

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [UweTrottmann/SeriesGuide#800]
Currently we can only have options for before:

![image](https://user-images.githubusercontent.com/5357526/120338915-53994480-c2fd-11eb-94f2-6d658f0bcab6.png)

Trying to set a negative value won't help, sadly.

Please offer options there for notifying us after the episode seems available.
The reason is that in many cases, it's not yet available due to different time zones.
You might even want to be able to set the notification time based on TV-show, but that's quite advanced.

In my case, for example, I think I'd like to be notified 2 hours later.

**Comment by UweTrottmann** [comment]
Due to historical reasons use the time offset feature to do this.

**Comment by AndroidDeveloperLB** [comment]
@UweTrottmann So if I set it to 2, will it notify me 2 hours later?

**Comment by UweTrottmann** [comment]
Yes, notifications respect the new "fake" release time.

**Comment by UweTrottmann** [comment]
Settings are supposed to be saved by Android device backup. Though this has never worked reliably in the past.

If you connect to Trakt or SeriesGuide Cloud your shows are saved there.

**Comment by AndroidDeveloperLB** [comment]
@UweTrottmann So with this, I should be safe:

![image](https://user-images.githubusercontent.com/5357526/120440026-d668e080-c38b-11eb-8234-8f62db8ae1a5.png)

?
If I remove the app and re-install it, I could see everything exactly as before removal?
