### ISSUE TITLE
Why isn't Esperanto updated from Crowdin?

### ISSUE THREAD

**Issue by jakubfabijan** [UweTrottmann/SeriesGuide#801]
There is a mostly done Esperanto translation on Crowdin, so why You updated every language but not Esperanto?

**Comment by UweTrottmann** [comment]
I'll repost my question from https://discuss.seriesgui.de/t/how-often-are-translations-between-crowdin-and-github-are-synced/1272/3?u=uwe

I just saw you contributed to the Esperanto translation, thanks for that! Out of curiosity I tried to find this language in Android settings on my device and it’s not available.

Do you know or have a device where Esperanto can even be used as the system language?

And in general I only add a new language if about 75% is translated, but 60% for Esperanto looks good.

**Comment by jakubfabijan** [comment]
Yes, I use my android with Esperanto setted as system language. It doesn't change language of Android UI, but every app that has Esperanto translation. Many esperantists uses locale changer app like [this one](https://play.google.com/store/apps/details?id=com.dogfeederz.localechanger&hl=en_US&gl=US).

**Comment by UweTrottmann** [comment]
OK, thanks for explaining! Next update will add the Esperanto file. 5479c401dd93255f5bc016fb40346527b6403448
