### ISSUE TITLE
SeriesGuide marks wrong episodes as watched on Trakt

### ISSUE THREAD

**Issue by Vampire** [UweTrottmann/SeriesGuide#803]
I just added this show to SeriesGuide: https://trakt.tv/shows/battlestar-galactica.
The problem is, SeriesGuide uses TMDB where there are only 22 episodes.
Trakt is still on TVDB for that show where are correctly 24 episodes.
Episode 1 on TMDB is episode 1-3 on TVDB.
Episode 2 on TMDB is episode 4 on TVDB.
If you now mark Episode 2 in SeriesGuide as watched, Episode 2 on Trakt is marked as watched but that doesn't match.

**Comment by UweTrottmann** [comment]
See https://discuss.seriesgui.de/t/tmdb-migration-issues-and-questions/1158 for why this is happening.

TL;DR: Trakt is in the process to switch to TMDB as the data source. You can contact them at support.trakt.tv. But note that they are very busy with this. So it might be best to just give them some time.

**Comment by Vampire** [comment]
Yeah, I know that problematic.
But it is marking wrong, not matching episodes.
I hoped there would be some way, maybe detect that Trakt is using different data source, or having an episode identifier, or matching by episode title maybe including some allowed fuzziness, ...

**Comment by UweTrottmann** [comment]
I don't really want to change that (e.g. send episode TMDB ID instead of currently show Trakt ID + season and episode number) in fear of breaking more things.
