### ISSUE TITLE
Snackbar string typo

### ISSUE THREAD

**Issue by Geeyun-JY3** [UweTrottmann/SeriesGuide#805]
**Describe the bug**
Snackbar string typo.

**To Reproduce**
1. Go to 'Movies' tab
2. Click on 'Search' icon
3. Click '︙' button of a movie card
4. Click 'Add to collection'
5. Snackbar shows 'Add to collection'

**Expected behavior**
I think it should be `Add to collection` should be`Added to collection`

**Screenshots**
![Screenshot_20210624175919](https://user-images.githubusercontent.com/49396421/123385891-a39bbc00-d5c8-11eb-856f-aed2fe391a5c.jpg)

**Smartphone (please complete the following information):**
 - Device: Mi 8
 - OS: Android 9 MIUI 10
 - Browser: Chrome
 - Version 59

**Additional context**

**Comment by UweTrottmann** [comment]
Thanks. But is no purpose that it repeats the action that is being executed. Also helps to avoid having to translate yet another string.

**Comment by Geeyun-JY3** [comment]
Oh I got it.
I just see that there is a [`Added to watchlist`](https://crowdin.com/translate/seriesguide-translations/14614/en-zhcn#6606084) string.  I assume it is used as the string of "Add to watchlist" snackbar. My bad.

**Comment by Geeyun-JY3** [comment]
Oh I got it.
I just see that there is a [`Added to watchlist`](https://crowdin.com/translate/seriesguide-translations/14614/en-zhcn#6606084) string.  I assume it is used as the string of "Add to watchlist" snackbar. My bad.

**Comment by Geeyun-JY3** [comment]
@UweTrottmann So where is the [`Added to watchlist`](https://crowdin.com/translate/seriesguide-translations/14614/en-zhcn#6606084) string used?

**Comment by UweTrottmann** [comment]
Only used when adding a show to your Trakt watchlist. I guess I'll remove that and use the `Add to watchlist` string instead.
