### ISSUE TITLE
Translation of season sometimes switches back to English

### ISSUE THREAD

**Issue by UweTrottmann** [UweTrottmann/SeriesGuide#807]
**Describe the bug**
On occasion and for random shows and for one ore more seasons (episode data is fetched by season) data returned by TMDb is in English instead of an available translation. The issue typically disappears within a day (e.g. with the next request).

**To Reproduce**
Use the app normally, shows update in the background.

- Request to get show and season info: https://developers.themoviedb.org/3/tv/get-tv-details

- Request to get episode info: https://developers.themoviedb.org/3/tv-seasons/get-tv-season-details
```
--> GET https://api.themoviedb.org/3/tv/4087/season/8?language=de&api_key=API_KEY
User-Agent: okhttp/4.9.1
```

**Expected behavior**
Episode overviews of a whole season should not randomly change their language.

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Version: any since TMDb switch

**Additional context**
- Forum discussion with 2 affected German users https://discuss.seriesgui.de/t/delayed-series-updates/1247
- Also observed this myself (also Germany based).
- Known shows that were affected: [X Files](https://www.themoviedb.org/tv/4087-the-x-files), [Brooklyn Nine-Nine](https://www.themoviedb.org/tv/48891-brooklyn-nine-nine), [The Walking Dead](https://www.themoviedb.org/tv/1402-the-walking-dead), Blue Bloods
- Impossible to reproduce, e.g. when running test request everything returns properly. Maybe a caching issue at TMDb?

**Comment by UweTrottmann** [comment]
Reported on TMDb forum: https://www.themoviedb.org/talk/60eeebdccf1afd0047172b85

**Comment by UweTrottmann** [comment]
Gotcha! Got a request returning English instead of German.

```
Request{method=GET, url=https://api.themoviedb.org/3/tv/48891/season/6?language=de&api_key=API_KEY}

Response{protocol=http/1.1, code=200, message=, url=https://api.themoviedb.org/3/tv/48891/season/6?language=de&api_key=API_KEY}
content-type: application/json;charset=utf-8
date: Fri, 16 Jul 2021 11:12:09 GMT
server: openresty
access-control-allow-origin: *
access-control-allow-methods: GET, HEAD, POST, PUT, DELETE, OPTIONS
access-control-expose-headers: ETag, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, Retry-After, Content-Length, Content-Range
cache-control: public, max-age=28800
x-memc: HIT
x-memc-key: b04e30571b7e80cb82b972ba31a370c0d4c9b826
x-memc-age: 5360
x-memc-expires: 9308
etag: W/"6fd128be5675fc1be6b727b53c02c78b"
vary: Accept-Encoding
x-cache: Hit from cloudfront
via: 1.1 560d8d35213ac925f8d05c5730db1582.cloudfront.net (CloudFront)
x-amz-cf-pop: FRA6-C1
x-amz-cf-id: f_Y7vPY1URbrHAIuknku3-sniLAjxj3yEHYHp9BrTyGGwq925oF-cw==
age: 13633
```

**Comment by unitb-ore** [comment]
Oh, wow! And what happens when using "de_DE" (or was it "de-DE"?) instead of "de", as someone suggested?

**Comment by UweTrottmann** [comment]
No, both codes are supported as indicated by the API docs. It shouldn't matter.

Headers of a network request:
```
Host: api.themoviedb.org
Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: okhttp/4.9.1
If-None-Match: W/"6fd128be5675fc1be6b727b53c02c78b"
```

**Comment by UweTrottmann** [comment]
I'll switch to using language + region tags, also unifying them for movies and shows as both are provided by TMDB now.

This should also solve #743.

**Comment by UweTrottmann** [comment]
#873 should fix this, assuming that using `de-DE` instead of `de` will help.

**Comment by unitb-ore** [comment]
Now SeriesGuide shows "Episode" as the episode title for ALL episodes of ALL seasons of ALL series. :-(

**Comment by UweTrottmann** [comment]
Actually, not shipped this, yet. Probably closed this out of habbit.

**Comment by UweTrottmann** [comment]
Will be released with 65.0.1.

**Comment by unitb-ore** [comment]
@UweTrottmann : Komisches Verhalten: Ich habe gerade die Serie "Bosch" (60585) in der App geöffnet und bin in Staffel 2 rein. Dort sah ich die deutschen Episodentitel. Nach einem Moment wechselten sie auf Englisch. Hier griff also im Hintergrund die Aktualisierung nach dem Reingehen in die Serie bzw. Staffel. Soweit verständlich. Wenn ich allerdings die Episoden-Infos via API abrufe, dann erhalte ich im gleichen Moment die korrekten deutschen Texte:
https://api.themoviedb.org/3/tv/60585/season/2?language=de&api_key=...

Wie kann das sein? Nutzt die App eine andere API-URL?

**Comment by UweTrottmann** [comment]
> Ansonsten bin ich schon auf v65.0.1 gespannt.

Also betrifft das obige noch die alte Version 64 und ist hinfällig? Die neue Version ist in den nächsten Stunden für alle Nutzer verfügbar.

**Comment by unitb-ore** [comment]
Ja, das betrifft die aktuelle Version, also v64(.0.7).

**Comment by unitb-ore** [comment]
Kein Problem mehr seit v65. :)
Lieben Dank!
