### ISSUE TITLE
Toast string typo

### ISSUE THREAD

**Issue by Geeyun-JY3** [UweTrottmann/SeriesGuide#808]
**Describe the bug**
Toast string typo

**To Reproduce**
1. Go to 'Shows' tab
2. Click on Search icon
3. Go to 'Discover' tab
4. Go to 'Watched' section
5. Click '+' icon
6. Toast [`Could not add %s`](https://crowdin.com/translate/seriesguide-translations/14614/en-zhcn?filter=basic&value=0#6606064) showed as `Could not add Could not add %s`

**Expected behavior**

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/49396421/125958880-0f222cd9-b7c9-4321-9182-eda40b73a952.png)

**Smartphone (please complete the following information):**
 - Device: Mi 8
 - OS: Android 9 MIUI 10
 - Browser: Chrome
 - Version 60-beta3

**Comment by UweTrottmann** [comment]
Good catch, thank you! Will be fixed with the next update.
