### ISSUE TITLE
Suddenly, all my already watched series show up again because 01*01 is marked as watched twice (without my consent ;))

### ISSUE THREAD

**Issue by klint** [UweTrottmann/SeriesGuide#814]
**Describe the bug**
Suddendly, one or 2 application updates ago, all series that I have already and full watched appeared again in the Series screen. And all those series show up in the Series screen at episode 01x02 (2nd episode of first season) .
The filter has not changed and is still set to "Unwatched" and "Favorites".
I have checked and and found out that all episodes of those series are well marked as "watched" though, except the first episode of the first season of every serie which is marked watched "(2)" times. This seems to be the root problem
I haven't done any manual action to mark them watched twice.

**Smartphone (please complete the following information):**
 - Device: Redmi Note 7
 - OS: Android 9
 - Browser: Firefox
 - V61-beta3

**Additional context**

**Comment by UweTrottmann** [comment]
Thanks for reporting. Is your SeriesGuide connected to Trakt or Cloud?

**Comment by klint** [comment]
My SeriesGuide is connected to Trakt but to not Cloud.

**Comment by UweTrottmann** [comment]
Hm, there have been no changes to the Trakt episode syncing code regarding plays since the feature was added in August last year.

However, the latest beta now properly calculates the next episode if episodes are rewatched. So it's possible those multiple watches existed for a while, but you only noticed them because of that change in SeriesGuide?

**Comment by klint** [comment]
Maybe. But ALL my past shows have the same issue.

**Comment by klint** [comment]
I have checked on Trakt itself, and it seems all the 01x01 episodes were marked as watched a second time on May 14th. 
Does this ring a bell? 
:)

**Comment by UweTrottmann** [comment]
This was around the time of SeriesGuide 58 https://github.com/UweTrottmann/SeriesGuide/blob/dev/CHANGELOG.md#version-58
But there weren't any Trakt sync related changes at that time.

**Comment by UweTrottmann** [comment]
😴 No response, closing.
