### ISSUE TITLE
Sync and Updates Issues

### ISSUE THREAD

**Issue by robant85** [UweTrottmann/SeriesGuide#818]
Opening a bug report for sync in the background. Whether or not the app is in the foreground, there have been many times, I’ll think a show hasn’t aired, but when I tap on an individual show, it updates. Even the full sync and update or download buttons don’t work until the show is clicked on. As per @UweTrottmann previous suggestions, I’ve had the app open for 10+ minutes and did several Download/Sync and Update/Sync and there were still several of my shows that didn’t update until I clicked on them. Tring to open an official bug, since there have been several app updates on beta and stable without the issue being considered.

**Comment by UweTrottmann** [comment]
This is happening because by default, if you do not interact with the app or a show, each show is updated at most every 7 days. But if you interact with a show, SeriesGuide will already check after 24 hours for updates.

In general see https://seriesgui.de/help#syncfail for potential solutions.

**Comment by robant85** [comment]
That's fine that it's the default option, but is there a way for it to FORCE all shows to update whether I tap on each or not? The "update & download all" button doesn't do it. Neither does "update & sync." If anything the bug is those buttons not actually doing what they say.

**Comment by UweTrottmann** [comment]
These buttons are mainly there for legacy reasons, you shouldn't use them at all. And yes, they force an update. But the network response may still be cached, so you might not see changes any sooner than just waiting.
