### ISSUE TITLE
The episode image can be still opened even if `Prevent spoilers` option enabled

### ISSUE THREAD

**Issue by Geeyun-JY3** [UweTrottmann/SeriesGuide#821]
**Describe the bug**
The episode image can be still opened even if `Prevent spoilers` option enabled

**To Reproduce**
1. Enable `Prevent spoilers` option
2. Go to 'Shows' tab
2. Click on any show in show list
3. Tap on episode image skeleton of any episode
4. The episode image is opened

**Expected behavior**
The episode image should not be opened.

**Screenshots**
![seriesguide](https://user-images.githubusercontent.com/49396421/140647781-a721ecde-4de4-4603-8c83-6210f92ed4fb.gif)

**Smartphone (please complete the following information):**
 - Device: Mi 8
 - OS: Android 9 MIUI 10
 - Browser: Chrome
 - Version 61

**Additional context**
no

**Comment by UweTrottmann** [comment]
Actually this is by design. Why would you tap to view the image if you don't want to see it?

**Comment by Geeyun-JY3** [comment]
If this is by design, I think that user can also tap to view the episode name and overview even if `Prevent spoilers` option enabled.

**Comment by Geeyun-JY3** [comment]
> If this is by design, I think that user can also tap to view the episode name and overview even if `Prevent spoilers` option enabled.

Or this should be an extra option when `Prevent spoilers` option enabled and I should make this a feature request?
