### ISSUE TITLE
Shows are not being properly synced from Trakt

### ISSUE THREAD

**Issue by danielpeng2** [UweTrottmann/SeriesGuide#830]
**Describe the bug**
When I connect to Trakt and sync shows/movies, my shows are not automatically added. I can see the watch history has been synced in the "History" tab, but the "Shows" tab doesn't display anything.

**To Reproduce**
1. Get a fresh install
2. Connect to Trakt
3. Wait for the sync to finish
4. Go to shows tab

**Expected behavior**
I expected all of my shows from Trakt to be added to SeriesGuide, I remember it worked this way before.

**Screenshots**
This is what I see in the shows tab:
![Screenshot_20211209-234312](https://user-images.githubusercontent.com/30786057/145519022-fa0dfbf0-7b33-4ccb-8734-6175d3a65557.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 12
 - Browser: Chrome
 - Version 61

**Comment by UweTrottmann** [comment]
This works as expected. You can add shows from your Trakt profile by pressing + and then the Watched, Collection or Watchlist buttons.

See also #741
