### ISSUE TITLE
Feature Request: Search by director

### ISSUE THREAD

**Issue by yephny** [UweTrottmann/SeriesGuide#835]
Searching movies by director, actor etc. would be great. I'm having a hard time adding movies to my watch / watched list one by one. 

This isn't directly supported on tmdb but they do have data on people and their role in movies. For instance, I should be able to search for Martin Scorsese, select "director" and see a list of all the movies he's directed.

**Comment by UweTrottmann** [comment]
Thanks! This was already requested in #746
