### ISSUE TITLE
Link filters with OR instead of AND condition

### ISSUE THREAD

**Issue by larena1** [UweTrottmann/SeriesGuide#838]
Selecting filters upcoming, unseen and to be continued will effectively hide shows which were canceled but still have unseen episodes.

It'd probably be better to link the filters with OR instead of AND.

**Comment by UweTrottmann** [comment]
If you filter by continuing shows, it will exclude canceled shows. I suggest to remove the continuing filter?

**Comment by larena1** [comment]
But I can't see continuing shows then when I remove the filter?

**Comment by UweTrottmann** [comment]
@larena1 Just disable it (empty box). Then it will display all shows regardless of status.

**Comment by larena1** [comment]
It will also show canceled shows then.

I want to see shows with unseen episodes (even if canceled) and continuing shows and shows with upcoming episodes.

**Comment by UweTrottmann** [comment]
> with unseen episodes (even if canceled) and continuing shows

Such complicated filters are not possible. To display both canceled and continuing shows requires to disable the Continuing filter.
