### ISSUE TITLE
Filter to hide collected episodes from Recent/Upcoming tabs

### ISSUE THREAD

**Issue by adrian-maurin** [UweTrottmann/SeriesGuide#851]
Hi,
It would be nice to be able to hide collected episode from those two tabs (like you can hide watched ones).
It could be useful to track missing episode from a collection.

Thanks anyway for this app, keep up!

**Comment by UweTrottmann** [comment]
Thanks for the suggestion! I'm going to put this on my internal suggestion list and close this issue (I'm trying to keep this for bugs only).
