### ISSUE TITLE
Watched series should have all their episodes watched/skipped

### ISSUE THREAD

**Issue by yephny** [UweTrottmann/SeriesGuide#869]
It looks like SeriesGuide considers a series to be watched as long as the last episode of its last season is marked as watched or skipped. I argue a better alternative is to mark a series as watched only if all its episodes have been watched or skipped.

The current implementation doesn't work quite as intended when you are watching a series, the later seasons of which you ignore/skip entirely. 

Here's an example. Imagine X has 2 seasons, but you know the latter season has nothing to do with the first one and is an absolute cash-grab. You start watching season 1 and mark its 1st episode as watched. There are 7 episodes remaining in the season. You go ahead and skip the entirety of season 2 while you're at it, just for it to get out of your way and to make sure the series is listed as having 7 episodes left in your watchlist. It turns out, however, SeriesGuide now lists it in your watched list, or more aptly, the "unwatched excuded" filter.

**Comment by UweTrottmann** [comment]
This is a trade-off and I decided that the app should look for the next episode watched based off the last one watched or skipped. In your case, SeriesGuide will pick the next episode from season 1 once you go in and mark the next episode from season 1 as watched/skipped.
