### ISSUE TITLE
Season 2 won't show up

### ISSUE THREAD

**Issue by yephny** [UweTrottmann/SeriesGuide#876]
**Describe the bug**
A show, Classroom of the Elite, has a second season according to TMDb, but only season 1 shows up in SeriesGuide.

**Comment by UweTrottmann** [comment]
Probably talking about https://www.themoviedb.org/tv/72517? The second season appears for me. Maybe try to remove and add the show again?

**Comment by yephny** [comment]
Re-adding the show worked. This is how it was before: ![season 1](https://a.pomf.cat/dqhrcv.png).

It's a bug regardless, wouldn't want to go through this for every series that I watch.

**Comment by UweTrottmann** [comment]
@yephny Check https://seriesgui.de/help#syncfail.

**Comment by yephny** [comment]
Thanks, I wasn't aware of the manual update feature.
