### ISSUE TITLE
Remove AntiFeatures Fdroid Please!

### ISSUE THREAD

**Issue by seniorm0ment** [UweTrottmann/SeriesGuide#879]
Would be greatly appreciated to remove antifeatures (at least from the fdroid release in izzys repo)

Its reporting the following:
- Has non-free dependencies
-  tracks or reports your activities
- Promotes non-free network services (understandable because its trakt.tv)

**Comment by UweTrottmann** [comment]
@seniorm0ment Thanks for your request. However, at this time I don't have any interest in publishing on F-Droid.
