### ISSUE TITLE
Should still be able to add shows when Trakt is down

### ISSUE THREAD

**Issue by goodevilgenius** [UweTrottmann/SeriesGuide#889]
**Describe the bug**
When syncing through Trakt, and I try to add a show to my list while Trakt is down (like right now), it fails with a message "Could not talk to Trakt, try again later"

**To Reproduce**
1. Wait for Trakt to be down
2. Go to "Shows"
3. Click on Add button
4. Search for a show, or select it from "Discover"
5. See error

**Expected behavior**
I should be able to add it to my list, but it will show that I haven't watched any episodes, and won't sync or be able to mark episodes watched, until Trakt comes back.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10E
 - OS: Android 
 - Version 12

**Additional context**
SeriesGuide v65.0.5, Database v50.
Installed through F-Droid.

**Comment by goodevilgenius** [comment]
That page shows that the only data from Trakt is release time, day, and country.

https://developers.themoviedb.org/3/tv/get-tv-details shows that `first_air_date` and `origin_country` are both available from TMDB.

So, you shouldn't *need* Trakt.

**Comment by UweTrottmann** [comment]
Note that if you can't wait you can disconnect Trakt for the time being. Then you should be able to add some shows. It appears Trakt's caching solution is still returning (cached) data for some (but obviously no user data), which allows the show to be added.

**Comment by ceptonit** [comment]
> Note that if you can't wait you can disconnect Trakt for the time being. Then you should be able to add some shows. It appears Trakt's caching solution is still returning (cached) data for some shows (but obviously no user data), which allows the show to be added.

I don't use Trakt at all (don't have an account with them) and yet can't add any shows ("Could not add NameOfShow Could not talk to Trakt. Try again later.").
Not sure since when. The shows I already have do update fine however.

```
12-17 10:30:09.3        AddShowTask D Starting to add next show...
12-17 10:30:09.8   Errors$Companion E show trakt lookup
com.battlelancer.seriesguide.util.ServerError: show trakt lookup: 503 
	at com.battlelancer.seriesguide.traktapi.TraktTools2.getShowByTmdbId(TraktTools2.kt:61)
	at com.battlelancer.seriesguide.shows.tools.GetShowTools.getShowDetails(GetShowTools.kt:63)
	at com.battlelancer.seriesguide.shows.tools.GetShowTools.getShowDetails$default(GetShowTools.kt:43)
	at com.battlelancer.seriesguide.shows.tools.AddUpdateShowTools.addShow(AddUpdateShowTools.kt:89)
	at com.battlelancer.seriesguide.shows.tools.AddShowTask.doInBackground(AddShowTask.java:212)
	at com.battlelancer.seriesguide.shows.tools.AddShowTask.doInBackground(AddShowTask.java:35)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

12-17 10:30:09.8        AddShowTask E Adding show failed: TRAKT_ERROR
12-17 10:30:09.8        AddShowTask D Finished adding show. (Result code: 5)
```

**Comment by 002gRTEah3mRYH** [comment]
> Note that if you can't wait you can disconnect Trakt for the time being. Then you should be able to add some shows. It appears Trakt's caching solution is still returning (cached) data for some shows (but obviously no user data), which allows the show to be added.

But how the app and Trakt will match again?

**Comment by UweTrottmann** [comment]
#892 will change to also allow adding shows if Trakt is down. SeriesGuide then will use some default values for the data loaded from Trakt (notably for time zone and release time).

@002gRTEah3mRYH See https://seriesgui.de/help#outage about that.
