### ISSUE TITLE
66.0.5 crashes on Android 6

### ISSUE THREAD

**Issue by TheArgentinian** [UweTrottmann/SeriesGuide#893]
As soon as I open the app, it crashes.

**Comment by UweTrottmann** [comment]
I could only find crashes on a Blackberry PRIV, is that your device? Also, has this been occurring only since this update?

**Comment by TheArgentinian** [comment]
> Thanks. I could only find crashes on a Blackberry PRIV, is that your device? Also, has this been occurring only since this update?

It's a Lenovo tablet (Yoga Tab 3). The  previous major update worked just fine.

**Comment by UweTrottmann** [comment]
😴 No response, closing.
