### ISSUE TITLE
Currently airing shows are moved to Watched when you see the latest (not the last) episode

### ISSUE THREAD

**Issue by yephny** [UweTrottmann/SeriesGuide#924]
**Describe the bug**
Unwatched shows that aren't finished shows are moved to Watched when you watch all episodes that have aired so far. 

**To Reproduce**
1. Set all episodes that have aired as watched of an unfinished show that's still airing.
2. You'll find it in Watched, only for it to move back to Unwatched when a new episode airs.

**Expected behavior**
I expect shows to remain in Unwatched until all the episodes (at least in the latest season) have been watched or skipped.

**Smartphone**
 - OS: Android 10, LineageOS

**Additional context**
This is really frustrating as I have to switch to the "Watched" filter and scroll to the bottom to see a show whose episode aired only hours ago (so it should still be at the top of Unwatched according to the Latest Episode sort I selected). I guess you'd need to take into account the episode count per season data as announced.

**Comment by UweTrottmann** [comment]
This is by design as SeriesGuide only considers released episodes as you have figured out.

Try this: add the Upcoming filter and maybe customize the range (e.g. 1 week or 1 month).

**Comment by yephny** [comment]
That helps, thanks.
