### ISSUE TITLE
Some series stuck on old episodes, new episodes not getting added

### ISSUE THREAD

**Issue by Rojetto** [UweTrottmann/SeriesGuide#925]
**Describe the bug**
For multiple series I added a long time ago, I am not getting current episodes anymore. Example:
- The Mandalorian, newest episode I see is S3E1 (should be S3E8)
- Last Week Tonight, newest episode I see is S10E2 (should be S10E8).

Tried manually syncing, to no effect. Also, for Mandalorian S3E1 it doesn't even load thumbnail or description.

**To Reproduce**
1. Open The Mandalorian from start screen
2. Switch to Episodes tab
3. Only see one episode in Season 3

**Expected behavior**
See 8 episodes in Season 3

**Screenshots**
![image](https://user-images.githubusercontent.com/777285/233082092-5e0e6d36-28eb-4ad8-93cf-d613efc775c7.png)

**Smartphone (please complete the following information):**
 - Device: OnePlus Nord
 - OS: OxygenOS 12.1
 - Version: 67.0.

**Comment by UweTrottmann** [comment]
There is an issue with OxygenOS 12 on OnePlus devices [where syncing only works with at least 10% of free storage space](https://discuss.seriesgui.de/t/no-update-to-verlauf-and-sync-to-trakt-since-jan-4th/1974/15?u=uwe).

Closing this. Let me know if this doesn't solve the issue and I'll re-open.
