### ISSUE TITLE
Cannot restore backup

### ISSUE THREAD

**Issue by nach0** [UweTrottmann/SeriesGuide#962]
**Describe the bug**
I created a backup for SeriesGuide on a previous installation. After resetting my phone and reinstalling SeriesGuide I cannot restore the backup from my previous installation.

**To Reproduce**
1. Create backups on 'Settings>Backup/Restore' and save in a location on your home folder.
2. Uninstall SeriesGuide and reinstall it.
3. Go to 'Settings>Backup/Restore'. Choose 'Restore Backup' and select all relevant options. Tap on 'Restore backup'
4. The app doesn't ask to locate the backup, instead it shows the message "There is no readable backup file"

**Expected behavior**
On step 4 above, the app opens a file browser and asks you to locate a backup file to load

**Smartphone (please complete the following information):**
 - Device: FairPhone 4
 - OS: iodéOS 4.7

**Comment by UweTrottmann** [comment]
You select the files by tapping the "Select file" button next to each checkbox. Are you saying there is no such checkbox? Can you provide a screenshot?

**Comment by nach0** [comment]
Of course! You're right. Sorry I'm blind, or dumb, or both. I totally ignored the "Select file" buttons, used to the single file/single button backups from other apps.
