### ISSUE TITLE
Migrate remaining usages of AsyncTask

### ISSUE THREAD

**Issue by UweTrottmann** [UweTrottmann/SeriesGuide#963]
Migrate to coroutines if possible, maybe similar to 74bdb6af

**Comment by barfour-kyei** [comment]
can I take this up?

**Comment by UweTrottmann** [comment]
@barfour-kyei Thanks for asking! As we never worked together before, maybe start with one small usage and submit a pull request for that. Then we'll go from there!

**Comment by barfour-kyei** [comment]
Sounds good!

**Comment by UweTrottmann** [comment]
Duplicate of #755
